---
- name: Validate EL7 Host
  hosts: all
  become: yes
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Give server time to boot
      delegate_to: localhost
      become: false
      pause:
        seconds: 180

    - name: Wait For SSH Port
      delegate_to: localhost
      become: false
      wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 22
        state: started
        timeout: 900

    - name: Hostname
      raw: hostname
      register: hostname_out
      changed_when: false

    - name: Running Kernel
      raw: uname -r
      register: kernel_out
      changed_when: false

    - name: Uptime
      raw: uptime
      register: uptime_out
      changed_when: false

    - name: Show Results
      debug:
        msg:
          - "Hostname : {{ hostname_out.stdout }}"
          - "Kernel   : {{ kernel_out.stdout }}"
          - "Uptime   : {{ uptime_out.stdout }}"
