---
- name: Configure Passwordless SSH
  hosts: "{{ target_hosts.split(',') | map('trim') | map('regex_replace', '$', '*') | join(',') }}"
  become: true
  gather_facts: false

  vars:
    windows_public_key: "files/authorized_key.pub"
    shared_private_key: "files/id_rsa"
    shared_public_key: "files/id_rsa.pub"

  tasks:

    - name: Ensure /root/.ssh exists
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Copy shared private key
      copy:
        src: "{{ shared_private_key }}"
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: "0600"
        force: yes

    - name: Copy shared public key
      copy:
        src: "{{ shared_public_key }}"
        dest: /root/.ssh/id_rsa.pub
        owner: root
        group: root
        mode: "0644"
        force: yes

    - name: Install Windows PuTTY public key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', windows_public_key) }}"
        manage_dir: false

    - name: Install shared Linux public key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', shared_public_key) }}"
        manage_dir: false

    - name: Ensure private key permissions
      file:
        path: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: "0600"

    - name: Ensure public key permissions
      file:
        path: /root/.ssh/id_rsa.pub
        owner: root
        group: root
        mode: "0644"

    - name: Ensure authorized_keys permissions
      file:
        path: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: "0600"

    - name: Verify authorized_keys
      stat:
        path: /root/.ssh/authorized_keys
      register: auth

    - name: Display status
      debug:
        msg:
          - "Passwordless SSH configured successfully."
          - "Host : {{ inventory_hostname }}"
          - "authorized_keys : {{ auth.stat.exists }}"
