---
- name: Provision CentOS 7 VMs with static IPs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_CENTOS_07"
    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"

    # Guest Credentials
    vm_root_user: "root"
    vm_root_password: "Root@123"

    # Inputs (Comma separated strings)
    vm_name: "http-server-01,tftp-server-01,tftp-server-02"
    vm_ip: "192.168.253.136,192.168.253.160,192.168.253.170"

  tasks:
    - name: Build vm_list from survey inputs
      set_fact:
        vm_list: "{{ vm_list | default([]) + [ {'name': item.0.strip(), 'ip': item.1.strip()} ] }}"
      loop: "{{ vm_name.split(',') | zip(vm_ip.split(',')) | list }}"

    - name: 1. Create and Power On VMs in vCenter
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        name: "{{ item.name }}"
        state: poweredon
        template: "{{ template_name }}"
        guest_id: "rhel7_64Guest"
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ item.ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            start_connected: true
        wait_for_customization: no
        wait_for_ip_address: no
      loop: "{{ vm_list }}"

    - name: 2. Wait for OS Boot (2 Minute Pause)
      ansible.builtin.pause:
        minutes: 2

    - name: 3. Add VMs to temporary inventory
      ansible.builtin.add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ vm_root_user }}"
        ansible_password: "{{ vm_root_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        vm_short_name: "{{ item.name }}"
        vm_domain: "{{ guest_domain }}"  # <-- Pass the domain variable here
        groups: "temp_group"
      loop: "{{ vm_list }}"

- name: Phase 2 - Login to Servers via IP and Configure
  hosts: temp_group
  gather_facts: no
  tasks:
    - name: 4. Explicitly wait for SSH connection
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

    - name: 5. Gather facts after connection is confirmed
      ansible.builtin.setup:

    - name: 6. Set Hostname inside the VM
      ansible.builtin.hostname:
        name: "{{ vm_short_name }}.{{ vm_domain }}"  # <-- Use the local host variable

    - name: 7. Final Verification
      ansible.builtin.debug:
        msg: "Successfully configured {{ inventory_hostname }} at {{ ansible_host }}"
