---
- name: Provision RockyOS VMs with static IPs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # vCenter Details
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_ROCKYOS_08"
    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"

    # Guest Credentials
    vm_root_user: "root"
    vm_root_password: "Root@123"

    # Inputs (Usually from AWX Survey)
    vm_name: "rocky-08-01"
    vm_ip: "192.168.253.133"

  tasks:
    - name: Build vm_list
      set_fact:
        vm_list: "{{ vm_list | default([]) + [ {'name': item.0, 'ip': item.1} ] }}"
      loop: "{{ vm_name.split(',') | zip(vm_ip.split(',')) | list }}"

    - name: 1. Create and Power On VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        template: "{{ template_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 4
          boot_firmware: efi
          secure_boot: false
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ item.ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            start_connected: true
        customization:
          domain: "{{ guest_domain }}"
          hostname: "{{ item.name }}"
        wait_for_customization: no
        wait_for_ip_address: no
      loop: "{{ vm_list }}"

    - name: 2. Force NIC Connection (Ansible 2.15 Syntax)
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.name }}"
        network_name: "{{ vm_network }}"
        connected: true
        start_connected: true
        state: present
        gather_network_info: false
      loop: "{{ vm_list }}"
      register: force_nic_output

    - name: 3. Wait for SSH to become reachable
      ansible.builtin.wait_for:
        host: "{{ item.ip }}"
        port: 22
        state: started
        delay: 15
        timeout: 300
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: 4. Verify Guest OS Networking
      ansible.builtin.setup:
      delegate_to: "{{ item.ip }}"
      vars:
        ansible_user: "{{ vm_root_user }}"
        ansible_password: "{{ vm_root_password }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      loop: "{{ vm_list }}"
      register: guest_facts

    - name: 5. Display Provisioning Summary
      ansible.builtin.debug:
        msg: 
          - "VM Name: {{ item.name }}"
          - "Status: SUCCESS"
          - "IP Address: {{ item.ip }}"
          - "Hostname set: {{ hostvars[item.ip]['ansible_hostname'] }}"
      loop: "{{ vm_list }}"
