---
- name: Provision RockyOS VMs with static IPs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_ROCKYOS_08"
    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"

    # Guest Credentials for SSH Login
    vm_root_user: "root"
    vm_root_password: "Root@123"

    # Inputs
    vm_name: "rocky-08-01"
    vm_ip: "192.168.253.133"

  tasks:
    - name: 1. Create and Power On VM in vCenter
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"  # <--- Added this to fix your error
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        guest_id: "rhel8_64Guest"
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ vm_ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            start_connected: true
        wait_for_customization: no
        wait_for_ip_address: no

    - name: 2. Force NIC Connection
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        network_name: "{{ vm_network }}"
        connected: true
        state: present

    - name: 3. Wait for SSH to become available
      ansible.builtin.wait_for:
        host: "{{ vm_ip }}"
        port: 22
        state: started
        delay: 10
        timeout: 300

    - name: 4. Define VM for SSH Login (Bridge to IP)
      ansible.builtin.add_host:
        name: "target_vm"
        ansible_host: "{{ vm_ip }}"
        ansible_user: "{{ vm_root_user }}"
        ansible_password: "{{ vm_root_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups: "temp_group"

- name: Phase 2 - Login to Server via IP and Configure
  hosts: temp_group
  gather_facts: yes
  tasks:
    - name: 5. Set Hostname inside the VM
      ansible.builtin.hostname:
        name: "{{ hostvars['localhost']['vm_name'] }}.{{ guest_domain }}"

    - name: 6. Final Verification
      ansible.builtin.debug:
        msg: 
          - "Successfully logged into: {{ ansible_host }}"
          - "Current Hostname inside OS: {{ ansible_hostname }}"
          - "OS Distribution: {{ ansible_distribution }}"
