---
- name: Provision VMs with static IPs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # vCenter Details
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    
    # Set this to your desired template
    template_name: "GOLDENTEMPLATE_CENTOS_07" 
    # template_name: "GOLDENTEMPLATE_ROCKYOS_08"

    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"

    # Guest Credentials
    vm_root_user: "root"
    vm_root_password: "Root@123"

    # Inputs (Survey)
    vm_name: "centos-07-01"
    vm_ip: "192.168.253.134"

  tasks:
    - name: Build vm_list
      set_fact:
        vm_list: "{{ vm_list | default([]) + [ {'name': item.0, 'ip': item.1} ] }}"
      loop: "{{ vm_name.split(',') | zip(vm_ip.split(',')) | list }}"

    - name: 1. Create and Power On VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        template: "{{ template_name }}"
        # HARDWARE BLOCK REMOVED: To inherit CPU/RAM from template and avoid HotRemove error
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ item.ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            start_connected: true
        customization:
          domain: "{{ guest_domain }}"
          hostname: "{{ item.name }}"
          dns_servers:
            - "192.168.253.151"
        wait_for_customization: no
        wait_for_ip_address: no
      loop: "{{ vm_list }}"

    - name: 2. Force NIC Connection (Ansible 2.15 Syntax)
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.name }}"
        network_name: "{{ vm_network }}"
        connected: true
        start_connected: true
        state: present
        gather_network_info: false
      loop: "{{ vm_list }}"

    - name: 3. Wait for SSH (Verify Connectivity)
      ansible.builtin.wait_for:
        host: "{{ item.ip }}"
        port: 22
        state: started
        delay: 20
        timeout: 400
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: 4. Verify Guest OS Networking (Gather Facts)
      ansible.builtin.setup:
      delegate_to: "{{ item.ip }}"
      vars:
        ansible_user: "{{ vm_root_user }}"
        ansible_password: "{{ vm_root_password }}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      loop: "{{ vm_list }}"
      register: guest_facts

    - name: 5. Final Summary Output
      ansible.builtin.debug:
        msg: 
          - "VM: {{ item.name }}"
          - "IP: {{ item.ip }}"
          - "OS Found: {{ hostvars[item.ip]['ansible_distribution'] | default('Unknown') }}"
          - "Hostname confirmed: {{ hostvars[item.ip]['ansible_hostname'] | default('N/A') }}"
      loop: "{{ vm_list }}"
