---
- name: Provision CentOS 7 VMs with static IPs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # vCenter Connectivity
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    
    # Template Selection (Switch as needed)
    template_name: "GOLDENTEMPLATE_CENTOS_07"

    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"

    # Guest Credentials
    vm_root_user: "root"
    vm_root_password: "Root@123"

    # Inputs (Survey)
    vm_name: "rocky-08-01"
    vm_ip: "192.168.253.133"

  tasks:
    - name: 1. Build vm_list
      set_fact:
        vm_list: "{{ vm_list | default([]) + [ {'name': item.0, 'ip': item.1} ] }}"
      loop: "{{ vm_name.split(',') | zip(vm_ip.split(',')) | list }}"

    - name: 2. Create and power on VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        template: "{{ template_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 4
          boot_firmware: efi
          secure_boot: false
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ item.ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            start_connected: true
        customization:
          domain: "{{ guest_domain }}"
          hostname: "{{ item.name }}"
        wait_for_customization: no
        wait_for_ip_address: no
      loop: "{{ vm_list }}"

    - name: 3. FORCE NIC CONNECTION
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.name }}"
        network_name: "{{ vm_network }}"
        connected: true
        start_connected: true
        state: present
        gather_network_info: false
      loop: "{{ vm_list }}"
      ignore_errors: yes

    - name: 4. Wait for SSH (Verify Connectivity)
      ansible.builtin.wait_for:
        host: "{{ item.ip }}"
        port: 22
        state: started
        delay: 20
        timeout: 400
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: 5. Verify Guest OS Networking (Gather Facts)
      ansible.builtin.setup:
      delegate_to: "{{ item.ip }}"
      vars:
        ansible_user: "{{ vm_root_user }}"
        ansible_password: "{{ vm_root_password }}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      loop: "{{ vm_list }}"
      register: guest_facts

    - name: 6. Final Summary Output
      ansible.builtin.debug:
        msg: 
          - "VM Name: {{ fact_pair.0.name }}"
          - "IP Address: {{ fact_pair.0.ip }}"
          - "Detected OS: {{ fact_pair.1.ansible_facts.ansible_distribution }}"
          - "Verified Hostname: {{ fact_pair.1.ansible_facts.ansible_hostname }}"
      loop: "{{ vm_list | zip(guest_facts.results) | list }}"
      loop_control:
        loop_var: fact_pair
