---
- name: Prepare VM list from AWX survey
  hosts: localhost
  gather_facts: no

  vars:
    # These come directly from AWX survey input
    hostnames: "{{ hostnames | default('') }}"
    ips: "{{ ips | default('') }}"

  tasks:
    - name: Split survey strings into lists
      set_fact:
        hostnames_list: "{{ hostnames.split(',') | map('trim') | list }}"
        ips_list: "{{ ips.split(',') | map('trim') | list }}"

    - name: Combine into vm_list
      set_fact:
        vm_list: "{{ vm_list | default([]) + [ {'hostnames': item.0, 'ips': item.1 } ] }}"
      loop: "{{ hostnames_list | zip(ips_list) | list }}"

    - name: Show vm_list
      debug:
        var: vm_list

- name: Manage VM Boot Firmware and Boot Order on ESXi
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.vmware

  vars:
    exsi_hostname: "192.168.253.128"
    exsi_username: "root"
    exsi_password: "admin$22"
    validate_certs: false

  tasks:

    - name: Power OFF VM
      vmware_guest:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item.hostnames }}"
        state: poweredoff
      loop: "{{ vm_list }}"

    - name: Set VM firmware to EFI (UEFI)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item.hostnames }}"
        boot_firmware: "efi"
      loop: "{{ vm_list }}"

    - name: Set boot order to PXE first (ethernet → disk)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item.hostnames }}"
        boot_order:
          - ethernet
          - disk
        enter_bios_setup: false
        boot_retry_enabled: false
        boot_delay: 0
      loop: "{{ vm_list }}"

    - name: Power on VM
      vmware_guest:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item.hostnames }}"
        state: poweredon
      loop: "{{ vm_list }}"

    - name: Switch boot order to disk first (disk → ethernet)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item.hostnames }}"
        boot_order:
          - disk
          - ethernet
        enter_bios_setup: false
        boot_retry_enabled: false
        boot_delay: 0
      loop: "{{ vm_list }}"

    - name: Wait for VM to respond to SSH (port 22)
      wait_for:
        host: "{{ item.ips }}"
        port: 22
        delay: 10
        timeout: 3600
        state: started
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: Remove old SSH host key from known_hosts
      shell: ssh-keygen -R {{ item.ips }} || true
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: Accept new SSH host key
      shell: ssh-keyscan -H {{ item.ips }} >> /tmp/known_hosts
      args:
        executable: /bin/bash
      loop: "{{ vm_list }}"
      delegate_to: localhost

- name: Check kernel version of new OS
  hosts: localhost
  gather_facts: no

  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/tmp/known_hosts -o StrictHostKeyChecking=no"

  tasks:

    - name: Check kernel version via SSH
      command: uname -r
      register: kernel_version
      delegate_to: "{{ item.ips }}"
      loop: "{{ vm_list }}"
      loop_control:
        index_var: loop_index

    - name: Display kernel version
      debug:
        msg: "Kernel version on {{ item.hostnames }} ({{ item.ips }}) is {{ kernel_version.results[loop_index].stdout }}"
      loop: "{{ vm_list }}"
      loop_control:
        index_var: loop_index
