- name: Enable UEFI and network boot on ESXi VM
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.vmware

  vars:
    exsi_hostname: "192.168.253.128"
    exsi_username: "root"
    exsi_password: "admin$22"
    validate_certs: false
    vm_name: "{{ vm_name }}"  # Use Tower survey to pass this

  tasks:
    - name: Set VM firmware to EFI (UEFI)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: false # Set to true if you have valid SSL certs
        name: "{{ vm_name }}"
        boot_firmware: "efi" # Set to 'bios' to revert

    - name: Set boot order to disk first, then network
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        boot:
          boot_order:
            - ethernet
          boot_delay: 0
          enter_bios_setup: false
          retry: false
          type: "efi"
        delegate_to: localhost
