- name: Enable UEFI and one-time network boot on ESXi VM
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.vmware

  vars:
    esxi_hostname: "192.68.253.128"
    esxi_username: "root"
    esxi_password: "Root@123"
    validate_certs: false

    vm_name: "{{ vm_name }}"  # Use Tower survey to pass this

  tasks:
    - name: Set VM firmware to UEFI
      vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        state: present
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          firmware: efi

    - name: Set one-time boot to network
      vmware_guest_boot_manager:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        boot_order:
          - network
          - disk
        boot_once: true
        enter_bios_setup: false
        boot_retry_enabled: false
        boot_delay: 0
