- name: Enable UEFI and one-time network boot on ESXi VM
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.vmware

  vars:
    esxi_hostname: "192.68.253.128"
    esxi_username: "root"
    esxi_password: "Root@123"
    validate_certs: false

    vm_name: "{{ vm_name }}"  # Use Tower survey to pass this

  tasks:
    - name: Set VM firmware to UEFI and configure boot
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        state: present
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          firmware: efi
        boot:
          boot_order:
            - network
            - disk
          enter_bios_setup: false
          boot_retry_enabled: false
          boot_delay: 0
          boot_once: true
