- name: Enable UEFI and network boot on ESXi VM
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.vmware

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    validate_certs: false
    vm_name: "{{ vm_name }}"  # Use Tower survey to pass this

  tasks:
    - name: Set VM firmware to EFI (UEFI)
      vmware_guest_boot_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false # Set to true if you have valid SSL certs
        name: "{{ vm_name }}"
        firmware: "efi" # Set to 'bios' to revert
        state: present
      delegate_to: localhost

    - name: Set boot order to network first
      vmware_guest_boot_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        boot_order:
          - ethernet
          - disk
        enter_bios_setup: false
        boot_retry_enabled: false
        boot_delay: 0
