- name: Manage VM Boot Firmware and Boot Order on ESXi
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.vmware

  vars:
    exsi_hostname: "192.168.253.128"
    exsi_username: "root"
    exsi_password: "admin$22"
    validate_certs: false
    vm_name: "{{ vm_name }}"
    vm_ip: "{{ vm_ip }}"  # Pass via Tower survey

  tasks:

    - name: Set VM firmware to EFI (UEFI)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        boot_firmware: "efi"

    - name: Set boot order to PXE first (ethernet → disk)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        boot_order:
          - ethernet
          - disk
        enter_bios_setup: false
        boot_retry_enabled: false
        boot_delay: 0

    - name: Power on VM
      vmware_guest:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        state: poweredon

    - name: Switch boot order to disk first (disk → ethernet)
      vmware_guest_boot_manager:
        hostname: "{{ exsi_hostname }}"
        username: "{{ exsi_username }}"
        password: "{{ exsi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        boot_order:
          - disk
          - ethernet
        enter_bios_setup: false
        boot_retry_enabled: false
        boot_delay: 0

    - name: Pause for 20 minutes to allow VM to boot
      pause:
       minutes: 20

    - name: Remove old SSH host key from known_hosts
      shell: ssh-keygen -R {{ vm_ip }} || true
      delegate_to: localhost

    - name: Accept new SSH host key
      shell: ssh-keyscan -H {{ vm_ip }} >> /tmp/known_hosts
      args:
       executable: /bin/bash
      delegate_to: localhost

- name: Check kernel version of new OS
  hosts: "{{ vm_name }}"
  gather_facts: no
  vars:
   ansible_ssh_common_args: "-o UserKnownHostsFile=/tmp/known_hosts -o StrictHostKeyChecking=no"
  tasks:

    - name: Check kernel version
      command: uname -r
      register: kernel_version

    - name: Display kernel version
      debug:
        msg: "Kernel version on {{ inventory_hostname }} is {{ kernel_version.stdout }}"
