---
- name: Migrate CentOS 7 to Rocky Linux 8 using ELevate
  hosts: "{{ target_hosts }}"
  become: yes
  vars:
    centos_vault_repo_file: /etc/yum.repos.d/CentOS-Base.repo
    elevate_repo_file: /etc/yum.repos.d/elevate.repo
    rocky_repo_file: /etc/leapp/files/leapp_upgrade_repositories.repo
    centos_patch_repo_file: /etc/yum.repos.d/centos-patch.repo
    repo_mount: "//192.168.31.87/ISO"
    mount_point: "/var/www/html/repo"
    username: "vigne"
    password: "Vigneshv12$"
    ansible_hostname: "ansible-server-01.vgs.com"
    ansible_python_interpreter: /usr/bin/python2.7

  pre_tasks:
    - name: Check current kernel version
      shell: uname -r
      register: kernel_version
      changed_when: false

    - name: Show message if already Rocky
      debug:
        msg: "Server is already Rocky Linux 8 (kernel {{ kernel_version.stdout }})"
      when: kernel_version.stdout is search("4.18.")

    - name: Stop play if already Rocky
      meta: end_play
      when: kernel_version.stdout is search("4.18.")

  tasks:
    - name: Check DNS resolution
      command: nslookup "{{ ansible_hostname }}"
      register: nslookup_result
      ignore_errors: yes
      changed_when: false

    - name: Configure DNS resolver
      copy:
        content: "nameserver 192.168.253.151"
        dest: /etc/resolv.conf
      when: nslookup_result.rc != 0

    - name: Find CentOS YUM repo files
      find:
        paths: /etc/yum.repos.d/
        patterns: 'CentOS-*'
      register: centos_repo_files

    - name: Remove CentOS YUM repo files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ centos_repo_files.files }}"

    - name: Create CentOS 7 patch repo
      copy:
        dest: "{{ centos_patch_repo_file }}"
        content: |
          [patch]
          name=patch-repo
          baseurl=http://http-server-01/repo/installed_rhel7
          enabled=1
          gpgcheck=0

    - name: Create vault.repo
      copy:
        content: |
          [base]
          name=CentOS Vault Base
          baseurl=https://vault.centos.org/7.9.2009/os/x86_64/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          [updates]
          name=CentOS Vault Updates
          baseurl=https://vault.centos.org/7.9.2009/updates/x86_64/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          [extras]
          name=CentOS Vault Extras
          baseurl=https://vault.centos.org/7.9.2009/extras/x86_64/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        dest: /etc/yum.repos.d/vault.repo

    - name: Remove libsolv if installed
      yum:
        name:
          - libsolv-0.6.34-4.el7.x86_64
          - libcomps.x86_64
        state: absent
      ignore_errors: yes

    - name: Make resolv.conf mutable
      command: chattr -i /etc/resolv.conf
      ignore_errors: yes

    - name: Get current kernel version
      shell: uname -r
      register: current_kernel
      changed_when: false

    - name: Set patch_needed
      set_fact:
        patch_needed: "{{ current_kernel.stdout.strip() != '3.10.0-1160.119.1.el7.x86_64' }}"

    - name: Show current kernel and patch need
      debug:
        msg: "Current kernel: {{ current_kernel.stdout.strip() }} | Patch needed: {{ patch_needed }}"

    - name: Update all CentOS 7 packages
      yum:
        name: "*"
        state: latest
      when: patch_needed

    - name: Reboot to reflect updates
      reboot:
        msg: "Reboot after applying CentOS 7 patches"
        reboot_timeout: 600
        pre_reboot_delay: 5
        post_reboot_delay: 30
      when: patch_needed

    - name: Backup existing .repo files
      shell: mkdir -p /etc/yum.repos.d/backup && mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2>/dev/null || true
      ignore_errors: yes

    - name: Create elevate.repo
      copy:
        dest: "{{ elevate_repo_file }}"
        content: |
          [elevate]
          name=ELevate-repo
          baseurl=http://http-server-01/repo/elevate/
          enabled=1
          gpgcheck=0
          [baseos]
          name=base-repo
          baseurl=http://http-server-01/repo/centos/
          enabled=1
          gpgcheck=0
          [basevault]
          name=CentOS Vault Base
          baseurl=https://vault.centos.org/7.9.2009/os/x86_64/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          [updatesvault]
          name=CentOS Vault Updates
          baseurl=https://vault.centos.org/7.9.2009/updates/x86_64/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          [extrasvault]
          name=CentOS Vault Extras
          baseurl=https://vault.centos.org/7.9.2009/extras/x86_64/
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

    - name: Install deltarpm
      yum:
        name: deltarpm
        state: present
      ignore_errors: yes

    - name: Install leapp and data
      yum:
        name:
          - leapp-upgrade
          - leapp-data-rocky
        state: present

    # --- CRITICAL FIX: Verify leapp-data-rocky integrity ---
    - name: Verify leapp-data-rocky is not corrupted
      shell: rpm -V leapp-data-rocky 2>/dev/null || yum reinstall -y leapp-data-rocky
      changed_when: false

    - name: Wait for RPM DB
      pause:
        seconds: 5

    # --- CRITICAL: Create and lock repo BEFORE preupgrade ---
    - name: Backup existing leapp repo file
      copy:
        src: "{{ rocky_repo_file }}"
        dest: "{{ rocky_repo_file }}.bak"
        remote_src: yes
      ignore_errors: yes

    - name: Create Rocky Linux 8 repo for leapp upgrade
      copy:
        dest: "{{ rocky_repo_file }}"
        content: |
          [rocky8-baseos]
          name=Rocky Linux 8 - BaseOS
          baseurl=http://http-server-01/srv/BaseOS/
          gpgcheck=0
          enabled=1
         
          [rocky8-appstream]
          name=Rocky Linux 8 - AppStream
          baseurl=http://http-server-01/srv/AppStream/
          gpgcheck=0
          enabled=1

    - name: Make repo file immutable
      command: chattr +i {{ rocky_repo_file }}

    - name: Unmount repo if mounted
      mount:
        path: "{{ mount_point }}"
        state: unmounted
      ignore_errors: yes

    - name: Remove repo from fstab
      lineinfile:
        path: /etc/fstab
        regexp: "{{ repo_mount | regex_escape() }}"
        state: absent

    - name: Run leapp preupgrade
      command: leapp preupgrade
      register: preupgrade_result
      ignore_errors: true

    - name: Show preupgrade result
      debug:
        var: preupgrade_result.stdout_lines

    - name: Remove incompatible kernel modules
      shell: |
        modprobe -r floppy || true
        modprobe -r pata_acpi || true

    - name: Answer leapp questions
      shell: |
        leapp answer --section authselect_check.confirm=True --add || true
        leapp answer --section remove_pam_pkcs11_module_check.confirm=True --add || true

    - name: Make repo mutable for upgrade
      command: chattr -i {{ rocky_repo_file }}
      ignore_errors: yes

    - name: Run leapp upgrade
      command: leapp upgrade
      register: upgrade_result
      ignore_errors: true

    - name: Show upgrade result
      debug:
        var: upgrade_result.stdout_lines

    - name: Wait before reboot
      pause:
        seconds: 10
      when: upgrade_result.rc == 0

    - name: Reboot into Rocky Linux
      reboot:
        reboot_timeout: 1800
        pre_reboot_delay: 15
      when: upgrade_result.rc == 0

    - name: Ensure Python 3
      raw: |
        if [ ! -x /usr/bin/python3 ]; then
          dnf install -y python3
        fi
      changed_when: false

    - name: Switch to Python 3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Verify OS after reboot
      shell: cat /etc/os-release
      register: os_release
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Show final OS
      debug:
        var: os_release.stdout_lines

    - block:
        - name: Remove old el7 kernels from weak-modules
          shell: |
            for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
              /usr/sbin/weak-modules --remove-kernel $k || true
            done

        - name: Remove old kernels via kernel-install
          shell: |
            for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
              /bin/kernel-install remove $k /lib/modules/$k/vmlinuz || true
            done

        - name: Find leftover el7 RPMs
          shell: |
            rpm -qa | grep -E '\.el[67]' | grep -vE '^(gpg-pubkey|libmoduled|katello-ca-consumer)' | sort
          register: el7_rpms

        - name: Save el7 package list
          copy:
            dest: /tmp/rhel7.txt
            content: "{{ el7_rpms.stdout }}"

        - name: Remove leftover el7 RPMs
          shell: |
            for i in $(cat /tmp/rhel7.txt); do
              echo "Removing $i"
              rpm -e $i --nodeps || true
            done
          when: el7_rpms.stdout != ""

        - name: Cleanup leapp and elevate
          dnf:
            name: 
              - leapp*
              - elevate*
            state: absent
          ignore_errors: yes

        - name: Remove leapp artifacts
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /lib/modules/*el7*
            - /var/log/leapp/
            - /var/lib/leapp/
            - /etc/leapp/
            - /root/tmp_leapp_py3
            - /boot/vmlinuz-*rescue*
            - /boot/initramfs-*rescue*

        - name: Reinstall current kernel
          shell: dnf reinstall -y kernel-core-$(uname -r)

        - name: Verify no el7 in grub
          shell: grubby --info=ALL | grep :"\el7" || echo "No old kernels in bootloader"
          register: grub_check

        - name: Show grub status
          debug:
            var: grub_check.stdout_lines

        - name: Verify normal initramfs contains kernel
          shell: |
            lsinitrd /boot/initramfs-$(uname -r).img | grep -q "kernel" && echo "OK" || echo "FAIL"
          register: initramfs_check

        - name: Show initramfs status
          debug:
            msg: "Initramfs for $(uname -r): {{ initramfs_check.stdout }}"

        - name: Final reboot
          reboot:
            msg: "Final reboot after cleanup"
            reboot_timeout: 600
            pre_reboot_delay: 10
            post_reboot_delay: 30

      when: upgrade_result.rc == 0

    - name: Final OS confirmation
      debug:
        msg: "Migration complete: {{ os_release.stdout_lines | join(' ') }}"
