---
- name: 🧹 Cleanup old CentOS 7 kernels and packages after ELevate migration
  hosts: all
  become: true
  gather_facts: true

  ####################################################################
  # Pre‑task guard: ensure we only run on Rocky Linux 8
  ####################################################################
  pre_tasks:
    - name: Ensure we are running on Rocky Linux 8
      fail:
        msg: "This playbook must be run only on Rocky Linux 8!"
      when: ansible_distribution != "Rocky" or ansible_distribution_major_version != "8"

  tasks:

    ################################################################
    # Basic repo/RPMDB/kernel cleanup (non-UEFI-specific)
    ################################################################
    - name: Ensure backup directory exists
      file:
        path: /etc/yum.repos.d/backup
        state: directory
        mode: '0755'

    - name: Move all repo files except backup directory
      shell: |
        shopt -s extglob
        mv /etc/yum.repos.d/!(backup) /etc/yum.repos.d/backup/ || true
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create Rocky Linux 8 repo
      copy:
        dest: /etc/yum.repos.d/base.repo
        content: |
          [rocky8-baseos]
          name=Rocky Linux 8 - BaseOS
          baseurl=http://http-server-01/repo/rocky8/BaseOS/
          gpgcheck=0
          enabled=1

          [rocky8-appstream]
          name=Rocky Linux 8 - AppStream
          baseurl=http://http-server-01/repo/rocky8/AppStream/
          gpgcheck=0
          enabled=1
        mode: '0644'

    - name: Backup current RPM database
      command: mv /var/lib/rpm /var/lib/rpm.bak-{{ ansible_date_time.epoch }}
      args:
        creates: "/var/lib/rpm.bak-{{ ansible_date_time.epoch }}"

    - name: Create new empty RPM db directory
      file:
        path: /var/lib/rpm
        state: directory
        mode: '0755'

    - name: Initialize new RPM database
      command: rpm --initdb

    - name: Restore Packages file from backup (if available)
      command: cp -av /var/lib/rpm.bak-{{ ansible_date_time.epoch }}/Packages /var/lib/rpm/
      ignore_errors: yes

    - name: Force remove stale __db* files
      shell: rm -f /var/lib/rpm/__db.* || true
      ignore_errors: yes

    - name: Rebuild RPM database
      command: rpm --rebuilddb
      ignore_errors: yes

    - name: Clean DNF cache
      command: dnf clean all
      ignore_errors: yes

    - name: Verify rpmdb works
      command: dnf list installed
      register: rpmdb_test
      ignore_errors: yes

    - debug:
        msg: "RPM DB status: {{ rpmdb_test.stdout | default('Failed to query rpmdb') }}"

    ####################################################################
    # 1. Pre-checks
    ####################################################################
    - name: List old el7 kernel directories
      shell: ls -d /lib/modules/*.el7* || true
      register: old_kernels
      changed_when: false

    ####################################################################
    # 2. Kernel Cleanup
    ####################################################################
    - name: Remove weak-modules for old el7 kernels
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /usr/sbin/weak-modules --remove-kernel $k || true
        done

    - name: Remove old kernels via kernel-install
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /bin/kernel-install remove $k /lib/modules/$k/vmlinuz || true
        done

    - name: Remove old kernel dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /lib/modules/*el7*

    ####################################################################
    # 3. RPM Cleanup
    ####################################################################
    - name: Find leftover el7 RPMs
      shell: |
        rpm -qa | grep -e '\.el[67]' | grep -vE '^(gpg-pubkey|libmoduled|katello-ca-consumer)' | sort
      register: el7_rpms
      changed_when: false

    - name: Save el7 package list
      copy:
        dest: /tmp/rhel7.txt
        content: "{{ el7_rpms.stdout }}"

    - name: Remove leftover el7 RPMs
      shell: |
        for i in $(cat /tmp/rhel7.txt); do
          echo "Removing $i"
          rpm -e $i --nodeps || true
        done
      when: el7_rpms.stdout != ""

    - name: Cleanup leapp packages
      yum:
        name:
          - leapp-pp
          - leapp-deps-el8
          - leapp-repository-deps-el8
        state: absent

    - name: Remove leapp logs and temp dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/log/leapp/
        - /root/tmp_leapp_py3
        - /var/lib/leapp/

    ####################################################################
    # 4. Kernel Reinstallation & Grub Verification
    ####################################################################
    - name: Reinstall current kernel-core
      shell: dnf reinstall -y kernel-core-$(uname -r)

    - name: Verify old kernels are not in grub
      shell: grubby --info=ALL | grep :"\el7" || echo "Old Kernels are not present in bootloader."
      register: grub_check
      changed_when: false

    - name: Show grub verification
      debug:
        var: grub_check.stdout_lines

    ####################################################################
    # 5. Rescue Image Rebuild
    ####################################################################
    - name: Remove old rescue images
      shell: rm -rf /boot/vmlinuz-*rescue* /boot/initramfs-*rescue*
      args:
        warn: false

    - name: Regenerate rescue entry
      shell: |
        /usr/lib/kernel/install.d/51-dracut-rescue.install add "$(uname -r)" /boot "/boot/vmlinuz-$(uname -r)"

    - name: List regenerated rescue images
      shell: ls /boot/vmlinuz-*rescue* /boot/initramfs-*rescue*
      register: rescue_files
      changed_when: false

    - name: Show rescue images
      debug:
        var: rescue_files.stdout_lines

    - name: Validate rescue initramfs contains correct kernel
      shell: |
        lsinitrd /boot/initramfs-*rescue*.img | grep -qm1 "$(uname -r)/kernel/" && echo OK || echo FAIL
      register: rescue_validation
      changed_when: false

    - name: Show rescue validation
      debug:
        var: rescue_validation.stdout_lines

    - name: Show grub entry for rescue kernel
      shell: grubby --info $(ls /boot/vmlinuz-*rescue*)
      register: grub_rescue
      changed_when: false

    - name: Show rescue grub entry
      debug:
        var: grub_rescue.stdout_lines

    ####################################################################
    # 6. Final Reboot
    ####################################################################
    - name: Final reboot after cleanup
      reboot:
        msg: "Final reboot after ELevate cleanup"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
