---
- name: Full RPMDB + Kernel Cleanup & Repair for Rocky Linux 8 (UEFI Safe)
  hosts: all
  become: true
  gather_facts: yes

  pre_tasks:
    - name: Ensure system is Rocky Linux 8
      assert:
        that:
          - ansible_distribution == "Rocky"
          - ansible_distribution_major_version == "8"
        fail_msg: "❌ This playbook can run ONLY on Rocky Linux 8!"
        success_msg: "✔ Rocky Linux 8 detected. Continuing..."

  tasks:

    ######################################################################
    # REPO FIX
    ######################################################################
    - name: Ensure backup directory exists
      file:
        path: /etc/yum.repos.d/backup
        state: directory
        mode: '0755'

    - name: Move all repo files except backup directory
      shell: |
        shopt -s extglob
        mv /etc/yum.repos.d/!(backup) /etc/yum.repos.d/backup/
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create Rocky Linux 8 repo
      copy:
        dest: /etc/yum.repos.d/base.repo
        content: |
          [rocky8-baseos]
          name=Rocky Linux 8 - BaseOS
          baseurl=http://http-server-01/repo/rocky8/BaseOS/
          gpgcheck=0
          enabled=1

          [rocky8-appstream]
          name=Rocky Linux 8 - AppStream
          baseurl=http://http-server-01/repo/rocky8/AppStream/
          gpgcheck=0
          enabled=1

    ######################################################################
    # RPMDB REPAIR
    ######################################################################
    - name: Backup current RPM database
      command: mv /var/lib/rpm /var/lib/rpm.bak-{{ ansible_date_time.epoch }}
      args:
        creates: "/var/lib/rpm.bak-{{ ansible_date_time.epoch }}"

    - name: Create new empty RPM db directory
      file:
        path: /var/lib/rpm
        state: directory
        mode: '0755'

    - name: Initialize new RPM database
      command: rpm --initdb

    - name: Restore Packages file from backup if present
      shell: cp -av /var/lib/rpm.bak-{{ ansible_date_time.epoch }}/Packages /var/lib/rpm/ || true

    - name: Remove stale __db files
      shell: rm -f /var/lib/rpm/__db.*

    - name: Rebuild RPM database
      command: rpm --rebuilddb

    - name: Clean DNF cache
      command: dnf clean all

    - name: Verify rpmdb works
      command: dnf list installed
      register: rpmdb_test
      ignore_errors: yes

    - debug:
        msg: "RPM DB status: {{ rpmdb_test.stdout | default('FAILED') }}"

    ######################################################################
    # REMOVE ALL OLD el7 KERNELS
    ######################################################################
    - name: Remove weak-modules for old el7 kernels
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /usr/sbin/weak-modules --remove-kernel $k || true
        done

    - name: Remove old kernels via kernel-install
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          kernel-install remove $k /lib/modules/$k/vmlinuz || true
        done

    - name: Find leftover el7 RPMs
      shell: |
        rpm -qa | grep -e '\.el7' | grep -vE '^(gpg-pubkey)' || true
      register: el7_rpms

    - name: Save el7 package list
      copy:
        dest: /tmp/rhel7.txt
        content: "{{ el7_rpms.stdout }}"

    - name: Remove leftover el7 RPMs
      shell: |
        for i in $(cat /tmp/rhel7.txt); do
          rpm -e $i --nodeps || true
        done

    ######################################################################
    # CLEANUP LEAPP
    ######################################################################
    - name: Cleanup leapp packages
      shell: dnf remove -y leapp\*

    - name: Remove leapp logs and old kernel dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /lib/modules/*el7*
        - /var/log/leapp/
        - /root/tmp_leapp_py3
        - /var/lib/leapp/
        - /boot/vmlinuz-*rescue*
        - /boot/initramfs-*rescue*

    ######################################################################
    # REINSTALL CURRENT KERNEL
    ######################################################################
    - name: Reinstall current kernel-core
      shell: dnf reinstall -y kernel-core

    - name: Verify old kernels are not in grub
      shell: grubby --info=ALL | grep :"\.el7" || echo "No el7 kernels in grub"
      register: grub_check

    - debug:
        var: grub_check.stdout_lines

    ######################################################################
    # UEFI RESCUE ENTRY FIX (YOUR PROBLEM)
    ######################################################################
    - name: Detect UEFI mode
      stat:
        path: /sys/firmware/efi
      register: efi_fw

    - name: Remove old CentOS rescue UEFI entry
      shell: |
        efibootmgr -v | grep -i "rescue" | awk -F"Boot" '{print $2}' | cut -c1-4 | \
        xargs -I {} efibootmgr -b {} -B
      when: efi_fw.stat.exists

    - name: Create new Rocky Linux rescue entry (UEFI)
      shell: |
        kernel=$(ls /boot/vmlinuz-*rescue* | head -1)
        initrd=$(ls /boot/initramfs-*rescue*.img | head -1)
        efibootmgr -c -d /dev/sda -p 1 -L "Rocky Linux Rescue" \
        -l "\EFI\rocky\shimx64.efi" \
        -u "root=/dev/sda2 ro rd.break initrd=${initrd} ${kernel}"
      when: efi_fw.stat.exists

    ######################################################################
    # REBUILD RESCUE INITRAMFS
    ######################################################################
    - name: Rebuild rescue initramfs
      shell: dracut -f /boot/initramfs-{{ ansible_kernel }}-rescue.img {{ ansible_kernel }}

    ######################################################################
    # REBOOT
    ######################################################################
    - name: Final reboot after cleanup
      reboot:
        msg: "Final reboot after cleanup"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30

    - name: Verify rescue initramfs contains modules
      shell: lsinitrd /boot/initramfs-{{ ansible_kernel }}-rescue.img | grep -q "modules/" && echo "OK" || echo "FAIL"
      register: rescue_modules_check

    - debug:
        var: rescue_modules_check.stdout
