---
- name: Full RPMDB + Kernel Cleanup & UEFI Rescue Repair for Rocky Linux 8
  hosts: all
  become: true
  gather_facts: yes

  pre_tasks:
    - name: Ensure system is Rocky Linux 8
      assert:
        that:
          - ansible_distribution == "Rocky"
          - ansible_distribution_major_version == "8"
        fail_msg: "❌ This playbook can run ONLY on Rocky Linux 8!"
        success_msg: "✔ Rocky Linux 8 detected. Continuing..."

  tasks:
    - name: Detect whether this machine is UEFI
      stat:
        path: /sys/firmware/efi
      register: efi_dir
      changed_when: false

    - name: Print boot mode
      debug:
        msg: "UEFI detected: {{ efi_dir.stat.exists }}"

    # --------------------------
    # RPMDB / repo / kernel cleanup (kept from original playbook)
    # (you already had these; unchanged except YAML correctness)
    # --------------------------
    - name: Ensure backup directory exists
      file:
        path: /etc/yum.repos.d/backup
        state: directory
        mode: '0755'

    - name: Move all repo files except backup directory
      shell: |
        shopt -s extglob
        mv /etc/yum.repos.d/!(backup) /etc/yum.repos.d/backup/ || true
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create Rocky Linux 8 repo
      copy:
        content: |
          [rocky8-baseos]
          name=Rocky Linux 8 - BaseOS
          baseurl=http://http-server-01/repo/rocky8/BaseOS/
          gpgcheck=0
          enabled=1

          [rocky8-appstream]
          name=Rocky Linux 8 - AppStream
          baseurl=http://http-server-01/repo/rocky8/AppStream/
          gpgcheck=0
          enabled=1
        dest: /etc/yum.repos.d/base.repo
        mode: '0644'

    - name: Backup current RPM database
      command: mv /var/lib/rpm /var/lib/rpm.bak-{{ ansible_date_time.epoch }}
      args:
        creates: "/var/lib/rpm.bak-{{ ansible_date_time.epoch }}"

    - name: Create new empty RPM db directory
      file:
        path: /var/lib/rpm
        state: directory
        mode: '0755'

    - name: Initialize new RPM database
      command: rpm --initdb

    - name: Restore Packages file from backup
      command: cp -av /var/lib/rpm.bak-{{ ansible_date_time.epoch }}/Packages /var/lib/rpm/
      ignore_errors: yes

    - name: Force remove stale __db* files
      shell: rm -f /var/lib/rpm/__db.* || true
      ignore_errors: yes

    - name: Rebuild RPM database
      command: rpm --rebuilddb

    - name: Clean DNF cache
      command: dnf clean all

    - name: Verify rpmdb works
      command: dnf list installed
      register: rpmdb_test
      ignore_errors: yes

    - debug:
        msg: "RPM DB status: {{ rpmdb_test.stdout | default('Failed to query rpmdb') }}"

    - name: List old el7 kernel directories
      shell: ls -d /lib/modules/*.el7* 2>/dev/null || true
      register: old_kernels
      changed_when: false

    - name: Remove weak-modules for old el7 kernels
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /usr/sbin/weak-modules --remove-kernel $k || true
        done
      when: old_kernels.stdout | length > 0

    - name: Remove old kernels via kernel-install
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /bin/kernel-install remove $k /lib/modules/$k/vmlinuz || true
        done
      when: old_kernels.stdout | length > 0

    - name: Find leftover el7 RPMs
      shell: |
        rpm -qa | grep -E '\.el[67]' | grep -vE '^(gpg-pubkey|libmoduled|katello-ca-consumer)' | sort || true
      register: el7_rpms
      changed_when: false

    - name: Save el7 package list
      copy:
        dest: /tmp/rhel7.txt
        content: "{{ el7_rpms.stdout | default('') }}"

    - name: Remove leftover el7 RPMs
      shell: |
        if [ -s /tmp/rhel7.txt ]; then
          while read -r pkg; do
            echo "Removing $pkg"
            rpm -e "$pkg" --nodeps || true
          done < /tmp/rhel7.txt
        fi
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Cleanup leapp packages
      shell: dnf remove -y 'leapp*' || true
      ignore_errors: yes

    - name: Remove leapp logs and old kernel dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /lib/modules/*el7*
        - /var/log/leapp/
        - /root/tmp_leapp_py3
        - /var/lib/leapp/
        - /boot/vmlinuz-*rescue*
        - /boot/initramfs-*rescue*
      ignore_errors: yes

    - name: Reinstall current kernel-core
      shell: dnf reinstall -y kernel-core || true
      ignore_errors: yes

    - name: Verify old kernels are not in grub (grubby)
      shell: grubby --info=ALL | grep -E '\.el7' || echo "Old Kernels are not present in the bootloader."
      register: grub_check
      changed_when: false

    - debug:
        var: grub_check.stdout_lines

    # --------------------------
    # UEFI-specific rescue / grub repair steps
    # --------------------------
    - name: Ensure efibootmgr and grub2 tools are available
      package:
        name:
          - efibootmgr
          - grub2-tools
          - grub2-tools-efi
          - shim-x64
        state: present
      ignore_errors: yes

    - name: Ensure at least one grub2 efi package is installed (try common names)
      package:
        name:
          - grub2-efi-x64
          - grub2-efi
          - grub2-efi-modules
        state: present
      ignore_errors: yes

    - name: Ensure /boot/efi mount point exists
      file:
        path: /boot/efi
        state: directory
        mode: '0755'

    - name: Ensure EFI partition is mounted (will try /boot/efi if not mounted)
      mount:
        path: /boot/efi
        state: mounted
      register: efi_mount
      ignore_errors: yes

    - name: Backup current /boot/efi/EFI/rocky directory if present
      shell: |
        if [ -d /boot/efi/EFI/rocky ]; then
          mkdir -p /root/efi_backup_{{ ansible_date_time.epoch }}
          cp -a /boot/efi/EFI/rocky /root/efi_backup_{{ ansible_date_time.epoch }} || true
        fi
      args:
        executable: /bin/bash
      changed_when: false

    - name: Rebuild rescue initramfs for current kernel
      shell: dracut -f /boot/initramfs-{{ ansible_kernel }}-rescue.img {{ ansible_kernel }}
      register: rebuild_rescue
      changed_when: true

    - name: Show rebuilt initramfs path
      debug:
        msg: "/boot/initramfs-{{ ansible_kernel }}-rescue.img rebuilt: {{ rebuild_rescue is defined }}"

    - name: Remove any rescue efi files under /boot/efi/EFI/rocky
      file:
        path: /boot/efi/EFI/rocky
        state: directory
      # ensure directory exists so we can delete only rescue files safely
    - name: Remove rescue-specific EFI files (wildcard)
      shell: rm -f /boot/efi/EFI/rocky/*rescue* || true
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Generate grub config for both BIOS and EFI locations
      shell: |
        grub2-mkconfig -o /boot/grub2/grub.cfg || true
        grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg || true
      args:
        executable: /bin/bash

    - name: Install GRUB EFI bootloader to the EFI directory (explicit target)
      shell: |
        # Use explicit target to avoid modinfo.sh errors.
        if command -v grub2-install >/dev/null 2>&1; then
          grub2-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id="Rocky" || \
          grub2-install --efi-directory=/boot/efi --bootloader-id="Rocky" || true
        fi
      args:
        executable: /bin/bash
      register: grub_install
      ignore_errors: yes

    - name: Show grub install output
      debug:
        var: grub_install.stdout_lines

    - name: Ensure loader file exists (grubx64.efi) before creating boot entry
      stat:
        path: /boot/efi/EFI/rocky/grubx64.efi
      register: grubx64_stat

    - name: Copy fallback grubx64.efi into place when missing
      shell: |
        # try to locate grubx64.efi in common locations and copy to /boot/efi/EFI/rocky/
        mkdir -p /boot/efi/EFI/rocky
        for src in /usr/lib/grub/x86_64-efi/core.efi /usr/lib/grub/x86_64-efi/grubx64.efi /usr/lib/grub2/x86_64-efi/grubx64.efi /usr/lib/grub2/x86_64-efi/core.efi; do
          if [ -f "$src" ]; then
            cp -a "$src" /boot/efi/EFI/rocky/grubx64.efi && break
          fi
        done
      args:
        executable: /bin/bash
      when: not grubx64_stat.stat.exists
      ignore_errors: yes

    - name: Gather current efibootmgr output
      shell: efibootmgr -v || true
      register: efiboot_out
      changed_when: false

    - name: Remove duplicate boot entries with label "Rocky Linux Rescue" or "Rocky Rescue"
      shell: |
        set -e
        efibootmgr -v | awk -F' *\\* ' '/Rocky Linux Rescue|Rocky Rescue|Rocky Rescue/ {print $1}' | sed 's/Boot//' | awk '{print $1}' | while read -r b; do
          if [ -n "$b" ]; then
            efibootmgr -b "$b" -B || true
          fi
        done
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create proper Rocky Linux Rescue EFI entry pointing to /EFI/rocky/grubx64.efi
      shell: |
        # Create new entry if one doesn't exist with correct loader path
        # Remove existing entry with identical label first (defensive)
        # Create entry
        efibootmgr -c -d /dev/sda -p 1 -L "Rocky Linux Rescue" -l "\\EFI\\rocky\\grubx64.efi" || true
      args:
        executable: /bin/bash
      register: efiboot_create
      ignore_errors: yes

    - name: Show efibootmgr creation output
      debug:
        var: efiboot_create.stdout_lines

    - name: Ensure boot order favors Rocky (put Rocky first)
      shell: |
        # read current BootOrder
        current=$(efibootmgr | awk -F': ' '/BootOrder/ {print $2}')
        # find Rocky or Rocky Linux Rescue entries
        rocky_boot=$(efibootmgr | awk '/Rocky( Linux)? Rescue|Rocky Linux|rocky/ {gsub(\"Boot\",\"\",$1); print $1; exit}')
        if [ -n "$rocky_boot" ]; then
          # put it first
          efibootmgr -o ${rocky_boot},$(echo $current | sed 's/,/ /g' | tr ' ' ',') || true
        fi
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Re-run grub2-mkconfig to ensure rescue entry is in grub.cfg (EFI)
      shell: grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg || true
      args:
        executable: /bin/bash

    - name: Final reboot after cleanup (only if requested)
      debug:
        msg: "Play completed. Consider rebooting the host to apply bootloader changes."
      # actual reboot is left manual; change this task to 'reboot:' if you want auto-reboot

    - name: Verify rescue initramfs contains modules (sanity)
      shell: lsinitrd /boot/initramfs-{{ ansible_kernel }}-rescue.img | grep -q "modules/" && echo "OK" || echo "FAIL"
      register: rescue_modules_check
      changed_when: false

    - debug:
        var: rescue_modules_check.stdout
