---
- name: Full RPMDB + Kernel Cleanup & Repair for Rocky Linux 8
  hosts: all
  become: true

  tasks:

    - name: Ensure backup directory exists
      file:
        path: /etc/yum.repos.d/backup
        state: directory
        mode: '0755'

    - name: Move all repo files except backup directory
      shell: |
        shopt -s extglob
        mv /etc/yum.repos.d/!(backup) /etc/yum.repos.d/backup/
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Backup current RPM database
      command: mv /var/lib/rpm /var/lib/rpm.bak-{{ ansible_date_time.epoch }}
      args:
        creates: "/var/lib/rpm.bak-{{ ansible_date_time.epoch }}"

    - name: Create new empty RPM db directory
      file:
        path: /var/lib/rpm
        state: directory
        mode: '0755'

    - name: Initialize new RPM database
      command: rpm --initdb

    - name: Restore Packages file from backup
      command: cp -av /var/lib/rpm.bak-{{ ansible_date_time.epoch }}/Packages /var/lib/rpm/
      ignore_errors: yes

    - name: Force remove stale __db* files
      shell: rm -f /var/lib/rpm/__db.*
      ignore_errors: yes

    - name: Rebuild RPM database
      command: rpm --rebuilddb

    - name: Clean DNF cache
      command: dnf clean all

    - name: Verify rpmdb works
      command: dnf list installed
      register: rpmdb_test
      ignore_errors: yes

    - debug:
        msg: "RPM DB status: {{ rpmdb_test.stdout | default('Failed to query rpmdb') }}"

    - name: List old el7 kernel directories
      shell: ls -d /lib/modules/*.el7* || true
      register: old_kernels
      changed_when: false

    - name: Remove weak-modules for old el7 kernels
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /usr/sbin/weak-modules --remove-kernel $k || true
        done

    - name: Remove old kernels via kernel-install
      shell: |
        for k in $(ls -d /lib/modules/*.el7* 2>/dev/null | xargs -n1 basename); do
          /bin/kernel-install remove $k /lib/modules/$k/vmlinuz || true
        done

    - name: Find leftover el7 RPMs
      shell: |
        rpm -qa | grep -e '\.el[67]' | grep -vE '^(gpg-pubkey|libmoduled|katello-ca-consumer)' | sort
      register: el7_rpms
      changed_when: false

    - name: Save el7 package list
      copy:
        dest: /tmp/rhel7.txt
        content: "{{ el7_rpms.stdout }}"

    - name: Remove leftover el7 RPMs
      shell: |
        for i in $(cat /tmp/rhel7.txt); do
          echo "Removing $i"
          rpm -e $i --nodeps || true
        done

    - name: Cleanup leapp packages
      shell: dnf remove leapp* -y

    - name: Remove leapp logs and old kernel dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /lib/modules/*el7*
        - /var/log/leapp/
        - /root/tmp_leapp_py3
        - /var/lib/leapp/
        - /boot/vmlinuz-*rescue*
        - /boot/initramfs-*rescue*

    - name: Install current kernel-core
      shell: dnf install -y kernel-core

    - name: Reinstall current kernel-core
      shell: dnf reinstall -y kernel-core

    - name: Rebuild standard initramfs for current kernel
      shell: dracut -f /boot/initramfs-{{ ansible_kernel }}.img {{ ansible_kernel }}
      register: rebuild_initramfs
      changed_when: true

    - name: Rebuild rescue initramfs for current kernel
      shell: dracut -f /boot/initramfs-{{ ansible_kernel }}-rescue.img {{ ansible_kernel }}
      register: rebuild_rescue
      changed_when: true

    - name: Verify rescue initramfs contains modules
      shell: lsinitrd /boot/initramfs-{{ ansible_kernel }}-rescue.img | grep -q "modules/" && echo "OK" || echo "FAIL"
      register: rescue_modules_check
      changed_when: false

    - debug:
        var: rescue_modules_check.stdout

    - name: Verify rescue image contains current kernel
      shell: |
        lsinitrd /boot/initramfs-*rescue*.img | grep -qm1 "$(uname -r)/kernel/" && echo "OK" || echo "FAIL"
      register: rescue_check
      changed_when: false

    - debug:
        var: rescue_check.stdout_lines

    - name: Final reboot after cleanup
      reboot:
        msg: "Final reboot after cleanup"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
