---
- name: Create a device in NetBox with IP and MAC
  hosts: "{{ target_hosts }}"
  become: yes
  vars:
    netbox_url: "http://192.168.253.134"
    netbox_token: "ee63f94d72c6c10a5b4e2cab4edbea9af0f18ac0"
    device_type_id: 1     # Replace with actual device type ID
    role_id: 1            # Replace with actual role ID
    site_id: 1            # Replace with actual site ID

  tasks:

    - name: Create tag if not exists
      uri:
        url: "{{ netbox_url }}/api/extras/tags/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
        body_format: json
        body:
          name: "{{ tag_name }}"
          slug: "{{ tag_name }}"
        status_code: [200, 201, 400]

    - name: Get tag ID
      uri:
        url: "{{ netbox_url }}/api/extras/tags/?name={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: tag_response

    - name: Set tag_id
      set_fact:
        tag_id: "{{ tag_response.json.results[0].id }}"

    - name: Create device
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
        body_format: json
        body:
          name: "{{ device_name }}"
          device_type: "{{ device_type_id }}"
          role: "{{ role_id }}"
          site: "{{ site_id }}"
          status: "active"
          tags: [{{ tag_id }}]
        return_content: yes
      register: device_response

    - name: Set device_id
      set_fact:
        device_id: "{{ device_response.json.id }}"

    - name: Create interface
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
        body_format: json
        body:
          device: "{{ device_id }}"
          name: "{{ interface_name }}"
          type: "1000base-t"
          mac_address: "{{ mac_address }}"
        return_content: yes
      register: interface_response

    - name: Set interface_id
      set_fact:
        interface_id: "{{ interface_response.json.id }}"

    - name: Assign IP address
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
        body_format: json
        body:
          address: "{{ ip_address }}"
          status: "active"
          assigned_object_type: "dcim.interface"
          assigned_object_id: "{{ interface_id }}"
