---
- name: Create multiple devices in NetBox
  hosts: rocky-08-02
  become: yes

  vars:
    netbox_url: "http://192.168.253.134"
    netbox_token: "ee63f94d72c6c10a5b4e2cab4edbea9af0f18ac0"
    device_type_id: 1
    role_id: 1
    site_id: 1

  tasks:

    - name: Loop through servers and include device creation tasks
      include_tasks: create_device.yml
      loop: "{{ servers }}"
      loop_control:
        loop_var: item
