---
- name: Create multiple devices in NetBox
  hosts: rocky-08-03
  become: yes

  vars:
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    device_type_id: 1
    role_id: 1
    site_id: 1

  tasks:

    - name: Parse servers string into list
      set_fact:
        servers_list: "{{ servers | from_yaml }}"

    - name: Debug parsed server list
      debug:
        var: servers_list

    - name: Loop through servers and include device creation tasks
      include_tasks: create_netbox_device.yml
      loop: "{{ servers_list }}"
      loop_control:
        loop_var: item
