---
- name: DNS Provisioning
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    # --- PHASE 0: PREPARE DATA ---
    - name: Load and normalize NetBox config context
      set_fact:
        # Use the first index since your debug showed it's a list
        nb_ctx: "{{ config_context[0] }}"
      when: config_context is defined and config_context | length > 0

    - name: Map Target IP
      set_fact:
        target_ip: "{{ ansible_host }}"

    # --- PHASE 1: DNS REGISTRATION ---
    - name: Execute Pi-hole script on DNS Server
      ansible.builtin.shell: "/root/pihole-customdns.sh --add {{ inventory_hostname }} {{ target_ip }}"
      delegate_to: 192.168.253.151 
      become: yes
      vars:
        # Explicitly pull nb_ctx from the current host's facts
        ansible_user: "{{ hostvars[inventory_hostname]['nb_ctx']['infra_dns_user'] }}"
        ansible_ssh_pass: "{{ hostvars[inventory_hostname]['nb_ctx']['infra_dns_pass'] }}"
      when: inventory_hostname not in ['dns-server-01.vgs.com', 'localhost']
