---
- name: Add multiple DNS entries to Pi-hole via API
  hosts: cent-dns-01
  become: true

  vars:
    pihole_api_script_path: /root/pihole_customdns_api/pihole-customdns.sh
    flask_server_ip: "192.168.253.134"
    selected_endpoint: "http://{{ flask_server_ip }}:5000/selected"

  tasks:

    - name: Fetch selected.json from Flask server
      uri:
        url: "{{ selected_endpoint }}"
        method: GET
        return_content: yes
      register: selected_vms

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from selected VMs
      set_fact:
        dns_entries: "{{ dns_entries + [ { 'dns_hostname': item.vm_name, 'dns_ip': item.vm_ip } ] }}"
      loop: "{{ selected_vms.json }}"

    - name: Add DNS entry using Pi-hole API script
      shell: >
        {{ pihole_api_script_path }} --add {{ item.dns_hostname }} {{ item.dns_ip }}
      args:
        chdir: "{{ pihole_api_script_path | dirname }}"
      loop: "{{ dns_entries }}"
      register: result

    - name: Show result
      debug:
        var: result.results
