---
- name: Step 1 & 2 - Integrated Hardware and OS Audit
  hosts: all
  gather_facts: no
  vars:
    esxi_user: "{{ config_context[0].exsi_username }}"
    esxi_pass: "{{ config_context[0].exsi_password }}"
    vm_user: "{{ config_context[0].vm_root_user }}"
    vm_pass: "{{ config_context[0].vm_root_password }}"
    esxi_host: "192.168.253.128"
    force_reconfig: false 

  tasks:
    # --- STEP 1: HARDWARE (ESXi Level) ---
    - name: Fix Hardware on ESXi (Delegated)
      raw: |
        VMNAME="{{ inventory_hostname_short }}"
        VMID=$(vim-cmd vmsvc/getallvms | grep " $VMNAME " | awk '{print $1}')
        [ -z "$VMID" ] && exit 0
        VMX_PATH=$(find /vmfs/volumes/ -name "${VMNAME}.vmx" | head -n 1)
        if ! grep -q "serial0.present = \"TRUE\"" "$VMX_PATH"; then
            WID=$(localcli vm process list | grep -A 1 "$VMNAME" | grep "World ID" | awk '{print $3}')
            [ ! -z "$WID" ] && localcli vm process kill --type=force --world-id=$WID && sleep 2
            sed -i '/serial0/d' "$VMX_PATH"
            VPORT=$((2000 + $VMID))
            printf 'serial0.present = "TRUE"\nserial0.yieldOnPoll = "TRUE"\nserial0.fileType = "network"\nserial0.fileName = "telnet://:%s"\nserial0.network.endPoint = "server"\n' "$VPORT" >> "$VMX_PATH"
            vim-cmd vmsvc/reload $VMID && sleep 1 && vim-cmd vmsvc/power.on $VMID
        fi
      delegate_to: "{{ esxi_host }}"
      vars:
        ansible_user: "{{ esxi_user }}"
        ansible_password: "{{ esxi_pass }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      when: inventory_hostname != esxi_host

    # --- STEP 2: GUEST OS (Internal Config) ---
    - name: Wait for VM to be reachable
      wait_for_connection:
        timeout: 300
      vars:
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pass }}"
      when: inventory_hostname != esxi_host

    - name: Apply OS Fix
      block:
        - name: Generate Dynamic GRUB script
          copy:
            dest: /tmp/enable-verbose-boot.sh
            mode: '0755'
            content: |
              #!/bin/bash
              # 1. DOWNLOAD MEMTEST
              mkdir -p /boot/efi/EFI/memtest
              curl -L -f -o /boot/efi/EFI/memtest/memtest.efi https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/mt86plus || exit 1

              # 2. DYNAMICALLY DETECT CURRENT KERNEL PARAMETERS (Prevents Initramfs errors)
              # This pulls your existing LVM/UUID configs so we don't overwrite them with wrong paths
              CURRENT_PARAMS=$(grep '^GRUB_CMDLINE_LINUX' /etc/default/grub | cut -d'"' -f2 | sed 's/console=ttyS0,[0-9]*//g' | sed 's/console=tty0//g' | xargs)
              NEW_PARAMS="console=tty0 console=ttyS0,115200 $CURRENT_PARAMS"

              # 3. CONFIGURE GRUB FILES
              IS_CENTOS7=$(grep -q "release 7" /etc/redhat-release && echo "true" || echo "false")
              LOADER="linux"
              [ "$IS_CENTOS7" == "true" ] && LOADER="linuxefi"

              # Update 40_custom
              cat <<EOC > /etc/grub.d/40_custom
              #!/bin/sh
              exec tail -n +3 \$0
              menuentry "MemTest86+ (Self-Compiled)" --class memtest86 {
                  insmod part_gpt
                  insmod fat
                  set root='hd0,gpt1'
                  $LOADER /EFI/memtest/memtest.efi console=ttyS0,115200
              }
              EOC
              chmod +x /etc/grub.d/40_custom

              # Update /etc/default/grub (Using Dynamic NEW_PARAMS)
              sed -i "s|^GRUB_CMDLINE_LINUX=.*|GRUB_CMDLINE_LINUX=\"$NEW_PARAMS\"|" /etc/default/grub
              sed -i "/^GRUB_TERMINAL=/d" /etc/default/grub
              echo 'GRUB_TERMINAL="serial console"' >> /etc/default/grub
              echo 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"' >> /etc/default/grub

              # 4. RUN MKCONFIG
              if [ -f /boot/efi/EFI/rocky/grub.cfg ]; then
                  grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
              elif [ -f /boot/efi/EFI/centos/grub.cfg ]; then
                  grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
              else
                  grub2-mkconfig -o /boot/grub2/grub.cfg
              fi

        - name: Execute Script and Reboot
          shell: /tmp/enable-verbose-boot.sh
        
        - name: Reboot
          reboot:
            reboot_timeout: 300
      vars:
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pass }}"
