[root@dns-server-01 ~]# ./final.sh
[*] Fetching ALL VMs from ESXi (192.168.253.128)...
==========================================================
Process VM: ipa-server-01? (y/n): y
[*] Phase 1: ESXi Hardware Check for ipa-server-01...
  -> ESXi Status: HARDWARE_OK
[*] Phase 2: Waiting for SSH on ipa-server-01 (192.168.253.191)...
  [*] Updating Remote ipa-server-01...
SSHPASS: Failed to run command: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k  100  160k    0     0  1000k      0 --:--:-- --:--:-- --:--:-- 1000k
Generating grub configuration file ...
Adding boot menu entry for EFI firmware configuration
done
Connection to 192.168.253.191 closed by remote host.
  [SUCCESS] ipa-server-01 updated and rebooting.
==========================================================
Process VM: ansible-server-01? (y/n): y
[*] Phase 1: ESXi Hardware Check for ansible-server-01...
  -> ESXi Status: HARDWARE_OK
[*] Phase 2: Waiting for SSH on ansible-server-01 (192.168.253.145)...
  [*] Updating Remote ansible-server-01...
SSHPASS: Failed to run command: No such file or directory
Configuring for Rocky / EL8+...
Generating grub configuration file ...
Adding boot menu entry for EFI firmware configuration
done
Connection to 192.168.253.145 closed by remote host.
  [SUCCESS] ansible-server-01 updated and rebooting.
