---
- name: Step 1 & 2 - Integrated Hardware and OS Audit
  hosts: all
  gather_facts: no
  vars:
    esxi_user: "{{ config_context[0].exsi_username }}"
    esxi_pass: "{{ config_context[0].exsi_password }}"
    vm_user: "{{ config_context[0].vm_root_user }}"
    vm_pass: "{{ config_context[0].vm_root_password }}"
    esxi_host: "192.168.253.128"
    force_reconfig: false 

  tasks:
    # --- STEP 1: HARDWARE (Unchanged) ---
    - name: Fix Hardware on ESXi (Delegated)
      raw: |
        VMNAME="{{ inventory_hostname_short }}"
        VMID=$(vim-cmd vmsvc/getallvms | grep " $VMNAME " | awk '{print $1}')
        [ -z "$VMID" ] && exit 0
        
        VMX_PATH=$(find /vmfs/volumes/ -name "${VMNAME}.vmx" | head -n 1)
        if ! grep -q "serial0.present = \"TRUE\"" "$VMX_PATH"; then
            WID=$(localcli vm process list | grep -A 1 "$VMNAME" | grep "World ID" | awk '{print $3}')
            [ ! -z "$WID" ] && localcli vm process kill --type=force --world-id=$WID && sleep 2
            sed -i '/serial0/d' "$VMX_PATH"
            VPORT=$((2000 + $VMID))
            printf 'serial0.present = "TRUE"\nserial0.yieldOnPoll = "TRUE"\nserial0.fileType = "network"\nserial0.fileName = "telnet://:%s"\nserial0.network.endPoint = "server"\n' "$VPORT" >> "$VMX_PATH"
            vim-cmd vmsvc/reload $VMID && sleep 1 && vim-cmd vmsvc/power.on $VMID
        fi
      delegate_to: "{{ esxi_host }}"
      vars:
        ansible_user: "{{ esxi_user }}"
        ansible_password: "{{ esxi_pass }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      when: inventory_hostname != esxi_host

    # --- STEP 2: GUEST OS ---
    - name: Wait for VM to be reachable
      wait_for_connection:
        timeout: 300
      vars:
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pass }}"
      when: inventory_hostname != esxi_host

    - name: Check if exact Serial Terminal config is active
      shell: grep '^GRUB_TERMINAL="serial console"' /etc/default/grub
      register: grub_check
      ignore_errors: yes
      changed_when: false
      vars:
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pass }}"
      when: inventory_hostname != esxi_host

    - name: Apply OS Fix
      when: 
        - inventory_hostname != esxi_host
        - (grub_check.rc != 0) or (force_reconfig | bool)
      block:
        - name: Generate Version-Specific GRUB script on VM
          copy:
            dest: /tmp/enable-verbose-boot.sh
            mode: '0755'
            content: |
              #!/bin/bash
              # Detect OS Version and Distribution
              IS_CENTOS7=$(grep -q "release 7" /etc/redhat-release && echo "true" || echo "false")
              
              if [ "$IS_CENTOS7" == "true" ]; then
                  # Config for CentOS 7
                  cat << 'EOG' > /etc/default/grub
              GRUB_TIMEOUT=10
              GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
              GRUB_DEFAULT=saved
              GRUB_DISABLE_SUBMENU=true
              GRUB_TERMINAL="serial console"
              GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200 crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap console=tty0"
              GRUB_DISABLE_RECOVERY="true"
              GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
              EOG
                  grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
              else
                  # Config for Rocky / EL8+
                  cat << 'EOG' > /etc/default/grub
              GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
              GRUB_DEFAULT=saved
              GRUB_DISABLE_SUBMENU=true
              GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200 crashkernel=auto resume=/dev/mapper/rl-swap rd.lvm.lv=rl/root rd.lvm.lv=rl/swap "
              GRUB_DISABLE_RECOVERY="true"
              GRUB_ENABLE_BLSCFG=true
              GRUB_TIMEOUT=10
              GRUB_TERMINAL="serial console"
              GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
              EOG
                  grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
              fi

        - name: Execute Generated Script
          shell: /tmp/enable-verbose-boot.sh
        
        - name: Reboot to apply changes
          reboot:
            reboot_timeout: 300
      vars:
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pass }}"
