- name: Run Foreman setup script from GitHub
  hosts: "{{ target_hosts }}"
  become: true
  tasks:

    - name: Download foreman.sh from GitHub to remote host
      become: true
      get_url:
        url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/foreman.sh"
        dest: "/tmp/foreman.sh"
        mode: '0755'
        remote_src: yes
    
    - name: Execute foreman.sh on remote host and store output
      become: true
      shell: "bash -l /tmp/foreman.sh | tee /tmp/foreman.log"
