- name: Run Foreman proxy setup script from GitHub
  hosts: "{{ target_hosts }}"
  become: true
  tasks:

    - name: Download foreman_proxy.sh from GitHub to remote host
      get_url:
        url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/foreman_proxy.sh"
        dest: "/tmp/foreman_proxy.sh"
        mode: '0755'
  
    - name: Create a file in tmp
      become: true
      file:
       path: /tmp/proxy_log.txt
       state: touch
       mode: '0644'

    - name: Execute foreman_proxy.sh on remote host and store output
      become: true
      shell: "/tmp/foreman_proxy.sh > /tmp/proxy_log.txt 2>&1"

    - name: Show Foreman proxy setup log
      command: cat /tmp/proxy_log.txt
      register: proxy_log

    - name: Print log contents
      debug:
        var: proxy_log.stdout_lines

