---
- name: Provision new Rocky servers from NetBox into Foreman
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - theforeman.foreman

  vars:
    netbox_url: "http://192.168.253.134"
    netbox_token: "ee63f94d72c6c10a5b4e2cab4edbea9af0f18ac0"
    foreman_server_url: "http://rocky-08-01.vgs.com"
    foreman_user: "admin"
    foreman_password: "r7DYDRyRQyVVnuwQ"
    host_root_pass: "Root@123"
    tag_name: "new-build-rockyos"  # <-- This will be overridden by survey input

  tasks:

    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Get interfaces from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_interfaces

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_ips

    - name: Build foreman_hosts list from NetBox data
      set_fact:
        foreman_hosts: >-
          {{
            netbox_devices.json.results | map('extract', {
              'vm_name': 'name',
              'vm_ip': netbox_ips.json.results | selectattr('assigned_object.device.name', 'equalto', item.name) | map(attribute='address') | list | first | default(''),
              'vm_mac': netbox_interfaces.json.results | selectattr('device.name', 'equalto', item.name) | map(attribute='mac_address') | list | first | default('')
            }) | list
          }}

    - name: Create hosts in Foreman
      theforeman.foreman.host:
        server_url: "{{ foreman_server_url }}"
        username: "{{ foreman_user }}"
        password: "{{ foreman_password }}"
        validate_certs: false
        name: "{{ item.vm_name }}"
        organization: "Default Organization"
        location: "Default Location"
        architecture: "x86_64"
        domain: "vgs.com"
        operatingsystem: "RockyLinux"
        medium: "Rocky 8 Remote"
        ptable: "Kickstart default"
        subnet: "vgs-subnet-rocky"
        hostgroup: "VGS HOSTS ROCKY 8"
        ip: "{{ item.vm_ip }}"
        mac: "{{ item.vm_mac }}"
        root_pass: "{{ host_root_pass }}"
        build: true
        enabled: true
      loop: "{{ foreman_hosts }}"
