- name: Run Foreman setup script from GitHub
  hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Download foreman.sh from GitHub
      get_url:
        url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/foreman.sh"
        dest: "/tmp/foreman.sh"
        mode: '0755'

    - name: Execute foreman.sh
      script: /tmp/foreman.sh
