- name: Run Foreman setup script from GitHub
  hosts: all
  become: true
  tasks:

    - name: Download foreman.sh from GitHub to remote host
      get_url:
        url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/foreman.sh"
        dest: "/tmp/foreman.sh"
        mode: '0755'

    - name: Ensure log file exists
      file:
        path: /tmp/foreman_log.txt
        state: touch
        mode: '0644'

    - name: Execute foreman.sh on remote host
      shell: /tmp/foreman.sh > /tmp/foreman_log.txt 2>&1
      register: foreman_run

    - name: Print Foreman setup log
      command: cat /tmp/foreman_log.txt
      register: foreman_log

    - name: Show log contents
      debug:
        var: foreman_log.stdout_lines
