---
- name: Collect host details
  hosts: all
  gather_facts: yes
  become: yes

  tasks:

    - name: Build structured host info
      set_fact:
        host_info:
          - name: "{{ ansible_hostname }}.vgs.com"
            ip: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask | ipaddr('prefix') }}"
            mac: "{{ ansible_default_ipv4.macaddress }}"
            interface: "{{ ansible_default_ipv4.interface }}"

    - name: Show final output
      debug:
        var: host_info
