- name: Configure HTTP server and prepare Rocky 8 repo
  hosts: "{{ target_hosts }}"
  become: yes

  vars:
    iso_path: "/var/www/html/repo/updated_rockyos.iso"
    mount_point: "/mnt"
    repo_mount: "//192.168.31.87/ISO"
	  mount_point_1: "/var/www/html/repo"
    local_repo_path: "/var/www/html/srv"

  tasks:

    - name: Create mount point directory
      file:
        path: "{{ mount_point_1 }}"
        state: directory
        mode: '0777'

    - name: Mount ISO share
      mount:
        path: "{{ mount_point_1 }}"
        src: "{{ repo_mount }}"
        fstype: cifs
        opts: "username={{ username }},password={{ password }},rw,dir_mode=0777,file_mode=0777,vers=3.0"
        state: mounted
      when: ansible_mounts | selectattr('mount', 'equalto', mount_point_1) | list | length == 0

    - name: Install required packages
      yum:
        name:
          - httpd
          - createrepo
        state: present

    - name: Create local repo directory
      file:
        path: "{{ local_repo_path }}"
        state: directory
        mode: '0755'

    - name: Create mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Mount RockyOS ISO
      mount:
        path: "{{ mount_point }}"
        src: "{{ iso_path }}"
        fstype: iso9660
        opts: loop,ro
        state: mounted

    - name: Copy contents from mounted ISO to local repo
      command: cp -a {{ mount_point }}/. {{ local_repo_path }}/
      args:
        creates: "{{ local_repo_path }}/BaseOS"

    - name: Rebuild BaseOS metadata
      command: createrepo --update {{ local_repo_path }}/BaseOS/

    - name: Rebuild AppStream metadata
      command: createrepo --update {{ local_repo_path }}/AppStream/

    - name: Configure HTTPD directory permissions
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "/var/www/html">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Enable HTTP & HTTPS firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
