- name: Configure HTTP server and prepare Rocky 8 repo
  hosts: all
  become: yes

  vars:
    # This maps the keys from your "patch-context" JSON into the nb_ctx object
    nb_ctx:
      repo_mount: "{{ repo_mount_path | default(repo_mount_path) }}"
      mount_point: "{{ repo_mount_point | default(repo_mount_point) }}"
      iso_user: "{{ iso_share_user | default(iso_share_user) }}"
      iso_pass: "{{ iso_share_pass | default(iso_share_pass) }}"
      ssh_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  tasks:
    - name: Create mount point directory for CIFS share
      file:
        path: "{{ nb_ctx.mount_point }}"
        state: directory
        mode: '0777'

    - name: Mount ISO share via CIFS
      mount:
        path: "{{ nb_ctx.mount_point }}"
        src: "{{ nb_ctx.repo_mount }}"
        fstype: cifs
        opts: "username={{ nb_ctx.iso_user }},password={{ nb_ctx.iso_pass }},rw,dir_mode=0777,file_mode=0777,vers=3.0"
        state: mounted

    - name: Install required packages
      yum:
        name:
          - httpd
          - createrepo
          - firewalld
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Disable selinux
      command: setenforce 0
      ignore_errors: yes

    - name: Configure HTTPD directory permissions
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "/var/www/html">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Enable HTTP & HTTPS firewall services
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
