- name: Configure HTTP server and prepare Rocky 8 repo
  hosts: all
  become: yes

  vars:
    repo_mount: "//192.168.31.87/ISO"
    mount_point_1: "/var/www/html/repo"
    username: "vigne"
    password: "Vigneshv12$"
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:

    - name: Create mount point directory for CIFS share
      file:
        path: "{{ mount_point_1 }}"
        state: directory
        mode: '0777'

    - name: Mount ISO share via CIFS
      mount:
        path: "{{ mount_point_1 }}"
        src: "{{ repo_mount }}"
        fstype: cifs
        opts: "username={{ username }},password={{ password }},rw,dir_mode=0777,file_mode=0777,vers=3.0"
        state: mounted

    - name: Install required packages
      yum:
        name:
          - httpd
          - createrepo
          - firewalld
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Disable selinux
      command: setenforce 0

    - name: Configure HTTPD directory permissions
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "/var/www/html">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Enable HTTP & HTTPS firewall services
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
