- name: Configure HTTP server and prepare Rocky 8 repo
  hosts: all
  become: yes

  vars:
    # This maps your "patch-context" JSON keys to the nb_ctx object style
    nb_ctx:
      repo_mount: "{{ repo_mount_path }}"
      mount_point: "{{ repo_mount_point }}"
      iso_user: "{{ iso_share_user }}"
      iso_pass: "{{ iso_share_pass }}"
      # Accessing the list of repositories from your JSON
      repo_list: "{{ repositories }}"
      ssh_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  tasks:
    - name: Install required packages
      yum:
        name:
          - httpd
          - createrepo
          - firewalld
          - cifs-utils
        state: present

    - name: Create base mount point directory
      file:
        path: "{{ nb_ctx.mount_point }}"
        state: directory
        mode: '0777'

    - name: Mount ISO share via CIFS
      mount:
        path: "{{ nb_ctx.mount_point }}"
        src: "{{ nb_ctx.repo_mount }}"
        fstype: cifs
        opts: "username={{ nb_ctx.iso_user }},password={{ nb_ctx.iso_pass }},rw,dir_mode=0777,file_mode=0777,vers=3.0"
        state: mounted

    - name: Ensure repository subdirectories exist
      file:
        path: "{{ nb_ctx.mount_point }}/{{ item.folder }}"
        state: directory
        mode: '0755'
      loop: "{{ nb_ctx.repo_list }}"

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Disable SELinux immediately
      command: setenforce 0
      ignore_errors: yes

    - name: Configure HTTPD directory permissions
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "{{ nb_ctx.mount_point }}">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Enable HTTP & HTTPS firewall services
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Run createrepo on repository folders
      command: "createrepo {{ nb_ctx.mount_point }}/{{ item.folder }}"
      loop: "{{ nb_ctx.repo_list }}"
      tags: update_repo
