- name: Configure HTTP server and prepare Rocky 8 repo
  hosts: all
  become: yes

  tasks:
    - name: Discover Context Variables
      set_fact:
        # This looks for the value in the top level, OR inside any of your context objects
        m_path: "{{ repo_mount_path | default(patch_context.repo_mount_path | default(pxe_rockyos_context.repo_mount_path | default(''))) }}"
        m_point: "{{ repo_mount_point | default(patch_context.repo_mount_point | default(pxe_rockyos_context.repo_mount_point | default(''))) }}"
        m_user: "{{ iso_share_user | default(patch_context.iso_share_user | default(pxe_rockyos_context.iso_share_user | default(''))) }}"
        m_pass: "{{ iso_share_pass | default(patch_context.iso_share_pass | default(pxe_rockyos_context.iso_share_pass | default(''))) }}"
        m_repos: "{{ repositories | default(patch_context.repositories | default([])) }}"

    - name: Verify Variables are Populated
      fail:
        msg: "CRITICAL: repo_mount_path or repo_mount_point is empty. Check AWX Extra Vars."
      when: m_path == "" or m_point == ""

    - name: Install required packages
      yum:
        name: [httpd, createrepo, firewalld, cifs-utils]
        state: present

    - name: Create base mount point directory
      file:
        path: "{{ m_point }}"
        state: directory
        mode: '0777'

    - name: Mount ISO share via CIFS
      mount:
        path: "{{ m_point }}"
        src: "{{ m_path }}"
        fstype: cifs
        opts: "username={{ m_user }},password={{ m_pass }},rw,dir_mode=0777,file_mode=0777,vers=3.0"
        state: mounted

    - name: Ensure repository subdirectories exist
      file:
        path: "{{ m_point }}/{{ item.folder }}"
        state: directory
        mode: '0755'
      loop: "{{ m_repos }}"

    - name: Configure HTTPD directory permissions
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "{{ m_point }}">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Enable Firewall and Start HTTPD
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: [firewalld, httpd]

    - name: Enable HTTP service in Firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Run createrepo
      command: "createrepo {{ m_point }}/{{ item.folder }}"
      loop: "{{ m_repos }}"
      when: m_repos | length > 0
