#!/bin/bash

# Generate SSH key (press enter 3 times automatically)
ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa <<< y

# Copy public key into authorized_keys locally
cd /root/.ssh
cp id_rsa.pub authorized_keys

# Configure first remote node
sshpass -p "Root@123" ssh -o StrictHostKeyChecking=no root@192.168.253.138 "
  mkdir -p /root/.ssh
  touch /root/.ssh/authorized_keys
"
sshpass -p "Root@123" scp -o StrictHostKeyChecking=no /root/.ssh/authorized_keys root@192.168.253.138:/root/.ssh/

# Configure second remote node
sshpass -p "Root@123" ssh -o StrictHostKeyChecking=no root@192.168.253.139 "
  mkdir -p /root/.ssh
  touch /root/.ssh/authorized_keys
"
sshpass -p "Root@123" scp -o StrictHostKeyChecking=no /root/.ssh/authorized_keys root@192.168.253.139:/root/.ssh/
