---
- name: Deploy MemTest86+ with OS-specific GRUB logic
  hosts: all
  become: yes
  vars:
    memtest_url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/mt86plus"
    # Use linuxefi for EL7, linux for everything else
    grub_linux_cmd: "{{ 'linuxefi' if ansible_distribution_major_version == '7' else 'linux' }}"

  tasks:
    - name: Download MemTest86+
      get_url:
        url: "{{ memtest_url }}"
        dest: "/boot/efi/EFI/memtest/memtest.efi"
        mode: '0755'
      # Ensure directory exists first
      register: download_bin
      until: download_bin is succeeded

    - name: Configure GRUB 40_custom with correct linux command
      copy:
        dest: "/etc/grub.d/40_custom"
        mode: '0755'
        content: |
          #!/bin/sh
          exec tail -n +3 $0
          
          menuentry "MemTest86+ (Self-Compiled)" --class memtest86 {
              insmod part_gpt
              insmod fat
              set root='hd0,gpt1'
              {{ grub_linux_cmd }} /EFI/memtest/memtest.efi
          }

    - name: Run grub2-mkconfig for EL7
      command: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
      when: ansible_distribution_major_version == "7"

    - name: Run grub2-mkconfig for EL8/9
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: ansible_distribution_major_version in ["8", "9"]
