---
- name: Install and Configure MemTest86 for UEFI
  hosts: rocky-8-servers
  gather_facts: yes
  vars:
    # Set this to the location of your memtest.efi binary
    # If you don't have it on a server, I've included a download step
  tasks:
    - name: Ensure Memtest EFI directory exists
      file:
        path: /boot/efi/EFI/memtest
        state: directory
        mode: '0755'

    - name: Download MemTest86 EFI binary
      # Using a direct link to the .efi is cleaner than unzipping the whole ISO
      get_url:
        url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/memtest.efi"
        dest: /boot/efi/EFI/memtest/memtest.efi
        mode: '0755'
        validate_certs: no
      register: download_bin

    - name: Add Memtest entry to GRUB custom configuration
      blockinfile:
        path: /etc/grub.d/40_custom
        marker: "# {mark} ANSIBLE MANAGED MEMTEST"
        block: |
          menuentry 'MemTest86 (UEFI Diagnostic)' --class memtest86 {
              insmod part_gpt
              insmod fat
              insmod search_fs_uuid
              # Dynamically find the EFI partition UUID for the search command
              search --no-floppy --fs-uuid --set=root {{ ansible_mounts | json_query('[?mount==`/boot/efi`].uuid | [0]') }}
              chainloader /EFI/memtest/memtest.efi
          }
      register: grub_entry

    - name: Rebuild GRUB Menu for UEFI
      command: grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
      when: download_bin.changed or grub_entry.changed

    - name: Reminder for Secure Boot
      debug:
        msg: "IMPORTANT: Ensure 'Secure Boot' is DISABLED in ESXi VM settings, or MemTest86 will not boot."
