---
- name: Deploy Self-Compiled MemTest86+ to UEFI Servers
  hosts: all
  become: yes
  vars:
    memtest_url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/mt86plus"
    memtest_path: "/boot/efi/EFI/memtest/memtest.efi"

  tasks:
    - name: Ensure MemTest directory exists on EFI partition
      file:
        path: "/boot/efi/EFI/memtest"
        state: directory
        mode: '0755'

    - name: Download MemTest86+ binary from GitHub
      get_url:
        url: "{{ memtest_url }}"
        dest: "{{ memtest_path }}"
        mode: '0755'

    - name: Configure GRUB 40_custom entry
      copy:
        dest: "/etc/grub.d/40_custom"
        mode: '0755'
        content: |
          #!/bin/sh
          exec tail -n +3 $0
          
          menuentry "MemTest86+ (Self-Compiled)" --class memtest86 {
              insmod part_gpt
              insmod fat
              search --no-floppy --fs-uuid --set=root {{ ansible_mounts | lib_get_efi_uuid }}
              linux /EFI/memtest/memtest.efi
          }
      # Note: We use a custom filter or manual shell if UUID logic gets complex
      # For simplicity, let's use a shell-friendly version below:

    - name: Alternative safe GRUB entry (Simple Version)
      blockinfile:
        path: /etc/grub.d/40_custom
        marker: "# {mark} ANSIBLE MANAGED MEMTEST"
        block: |
          menuentry "MemTest86+ (Self-Compiled)" --class memtest86 {
              insmod part_gpt
              insmod fat
              set root='hd0,gpt1'
              linux /EFI/memtest/memtest.efi
          }

    - name: Regenerate GRUB configuration
      command: grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
      # For Rocky 9, you would target /boot/grub2/grub.cfg instead
