---
- name: Install MemTest86+ Only
  hosts: all
  become: yes
  vars:
    memtest_url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/mt86plus"
    efi_path: "/boot/efi/EFI/memtest"

  tasks:
    - name: Ensure Memtest directory exists
      file:
        path: "{{ efi_path }}"
        state: directory
        mode: '0755'

    - name: Download MemTest binary
      get_url:
        url: "{{ memtest_url }}"
        dest: "{{ efi_path }}/memtest.efi"
        mode: '0755'

    - name: Create 40_custom entry
      copy:
        dest: /etc/grub.d/40_custom
        mode: '0755'
        content: |
          #!/bin/sh
          exec tail -n +3 $0
          menuentry "MemTest86+ (Self-Compiled)" --class memtest86 {
              insmod part_gpt
              insmod fat
              set root='hd0,gpt1'
              {{ 'linuxefi' if ansible_distribution_major_version == '7' else 'linux' }} /EFI/memtest/memtest.efi
          }

    - name: Regenerate GRUB configuration
      shell: |
        if [ -f /boot/efi/EFI/rocky/grub.cfg ]; then TARGET="/boot/efi/EFI/rocky/grub.cfg"
        elif [ -f /boot/efi/EFI/centos/grub.cfg ]; then TARGET="/boot/efi/EFI/centos/grub.cfg"
        else TARGET="/boot/grub2/grub.cfg"; fi
        grub2-mkconfig -o $TARGET
