---
- name: Deploy MemTest86+ with OS-specific GRUB logic
  hosts: all
  become: yes
  vars:
    memtest_url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/mt86plus"
    memtest_efi_path: "/boot/efi/EFI/memtest/memtest.efi"

  tasks:
    - name: Ensure EFI directory exists
      file:
        path: "/boot/efi/EFI/memtest"
        state: directory
        mode: '0755'

    - name: Download MemTest86+ binary from GitHub
      get_url:
        url: "{{ memtest_url }}"
        dest: "{{ memtest_efi_path }}"
        mode: '0755'

    - name: Configure GRUB 40_custom
      copy:
        dest: "/etc/grub.d/40_custom"
        mode: '0755'
        content: |
          #!/bin/sh
          exec tail -n +3 $0
          
          menuentry "MemTest86+ (Self-Compiled)" --class memtest86 {
              insmod part_gpt
              insmod fat
              set root='hd0,gpt1'
              linux /EFI/memtest/memtest.efi
          }

    - name: Update GRUB for EL7 (CentOS 7)
      command: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
      when: ansible_distribution_major_version == "7"

    - name: Update GRUB for EL8/9 (Rocky/CentOS Stream)
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: ansible_distribution_major_version in ["8", "9"]

    - name: Optional - Refresh Rocky EFI stub (EL8/9 only)
      command: grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
      when: 
        - ansible_distribution == "Rocky"
        - ansible_distribution_major_version in ["8", "9"]
      failed_when: false # Don't fail if the file doesn't exist
