---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  gather_facts: yes
  vars:
    pihole_url: "https://pi.hole"  # or use https://192.168.253.151
    pihole_password: "Root@123"
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"  # <-- replace with your real token
    netbox_tag: "existing-centos"

  tasks:
    # === 1. Get devices tagged in NetBox ===
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ netbox_tag }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        status_code: 200
      register: netbox_devices

    # === 2. Get IPs for those devices ===
    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device={{ item.id }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_ips

    # === 3. Build dns_entries list ===
    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {'dns_hostname': item.name, 'dns_ip': (netbox_ips.results | selectattr('item.id', 'equalto', item.id) | map(attribute='json.results') | flatten | first | default({}) ).address | default('') | regex_replace('/.*','') } ] }}"
      loop: "{{ netbox_devices.json.results }}"
      when: (netbox_ips.results | selectattr('item.id', 'equalto', item.id) | map(attribute='json.results') | flatten | first | default({}) ) != {}

    # === 4. Authenticate to Pi-hole (get SID + CSRF) ===
    - name: Authenticate with Pi-hole API
      uri:
        url: "{{ pihole_url }}/api/auth"
        method: POST
        body_format: json
        body:
          password: "{{ pihole_password }}"
        return_content: yes
        validate_certs: no
      register: pihole_auth

    - name: Extract Pi-hole session values
      set_fact:
        pihole_sid: "{{ pihole_auth.json.session.sid }}"
        pihole_csrf: "{{ pihole_auth.json.session.csrf }}"

    # === 5. Get existing DNS entries from Pi-hole ===
    - name: Get existing DNS entries from Pi-hole
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts"
        method: GET
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
        return_content: yes
        validate_certs: no
      register: existing_pihole_dns

    - name: Normalize Pi-hole response safely
      set_fact:
        existing_dns_names: "{{ existing_pihole_dns.json.data | map(attribute='name') | list | default([]) }}"
      when: existing_pihole_dns.json.data is defined

    # === 6. Add missing entries only ===
    - name: Add DNS entries using Pi-hole API script
      command: "/root/pihole_customdns_api/pihole-customdns.sh --add {{ item.dns_hostname }} {{ item.dns_ip }}"
      args:
        chdir: "/root/pihole_customdns_api"
      loop: "{{ dns_entries }}"
      when: item.dns_hostname not in existing_dns_names | default([])
      register: add_results
      ignore_errors: yes

    # === 7. Show final results ===
    - name: Show final results
      debug:
        var: add_results.results
