# ============================================================
# 1. Collect facts from all target hosts
# ============================================================
- name: Collect facts from all servers
  hosts: "{{ target_hosts.split(',') | map('trim') | list }}"
  gather_facts: yes
  become: yes
  vars:
    cluster_name: "{{ cluster_name }}"     # passed from Tower/AWX survey
    site_name: "{{ site_name }}"           # passed from Tower/AWX survey
    cluster_type: "{{ cluster_type }}"     # passed from Tower/AWX survey
    cluster_group_name: "{{ cluster_group_name }}"

  tasks:
    - name: Build server_info from facts
      set_fact:
        server_info:
          name: "{{ ansible_hostname }}.vgs.com"
          ip: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.prefix }}"
          mac: "{{ ansible_default_ipv4.macaddress }}"
          interface: "{{ ansible_default_ipv4.interface }}"
          serial: "{{ ansible_product_serial | default('') | regex_replace('[^a-zA-Z0-9]', '') | truncate(50, True, '') }}"
          cluster: "{{ cluster_name }}"  # From Tower/AWX Survey
          site: "{{ site_name }}"       # From Tower/AWX Survey

# ============================================================
# 2. Push collected servers into NetBox
# ============================================================
- name: Push collected servers into NetBox
  hosts: rocky-08-02
  gather_facts: no

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "e3b30f093150844cb025c4b5b91c49f4b8285092"
    device_type_id: 1
    role_id: 1

  tasks:
    - name: Aggregate servers_list from hostvars
      set_fact:
        servers_list: "{{ target_hosts.split(',') | map('trim') | map('extract', hostvars, 'server_info') | list }}"

    - name: Loop through servers
      include_tasks: modified_create_netbox_device.yml
      loop: "{{ servers_list }}"
      loop_control:
        loop_var: item
