---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: true

  vars:
    pihole_api_script_path: /root/pihole_customdns_api/pihole-customdns.sh
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    tag_name: "existing-centos"

  tasks:
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_ips

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {
          'hostname': item.name,
          'ip': (netbox_ips.json.results
            | selectattr('assigned_object.device.name', 'equalto', item.name)
            | map(attribute='address')
            | map('regex_replace', '/.*$', '')
            | list | first | default(''))
        } ] }}"
      loop: "{{ netbox_devices.json.results }}"

    - name: Show prepared DNS entries
      debug:
        var: dns_entries

    - name: Get existing DNS entries from Pi-hole
      shell: "curl -sk http://192.168.253.151/admin/api.php?list=localdns"
      register: existing_dns_raw

    - name: Parse existing Pi-hole DNS entries
      set_fact:
        existing_dns: "{{ (existing_dns_raw.stdout | from_json).data | map(attribute='name') | list }}"
      when: existing_dns_raw.stdout | length > 0

    - name: Add DNS entries only if not present
      shell: >
        {{ pihole_api_script_path }} --add {{ item.hostname }} {{ item.ip }}
      args:
        chdir: "{{ pihole_api_script_path | dirname }}"
      loop: "{{ dns_entries }}"
      when: item.hostname not in existing_dns
      register: dns_add_results

    - name: Show result
      debug:
        var: dns_add_results.results
