---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: localhost
  gather_facts: false
  vars:
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    pihole_host: "192.168.253.151"
    pihole_dns_domain: "vgs.com"

  tasks:

    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag=existing-centos"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [{'hostname': item.device.name.split('.')[0], 'ip': item.primary_ip4.address.split('/')[0] }] }}"
      loop: "{{ netbox_devices.json.results | map(attribute='interfaces') | list | flatten(levels=1) }}"
      when: item.primary_ip4 is defined and item.primary_ip4.address is defined

    - name: Get existing DNS entries from Pi-hole
      uri:
        url: "http://{{ pihole_host }}/admin/api.php?list=forwarding"
        method: GET
        return_content: yes
      register: pihole_existing

    - name: Parse existing DNS hostnames
      set_fact:
        existing_hosts: "{{ pihole_existing.json.forwarding | map(attribute='name') | list }}"
      when: pihole_existing.json.forwarding is defined

    - name: Add missing DNS entries to Pi-hole
      uri:
        url: "http://{{ pihole_host }}/admin/api.php?list=forwarding"
        method: POST
        body_format: json
        body:
          name: "{{ item.hostname }}"
          ip: "{{ item.ip }}"
          domain: "{{ pihole_dns_domain }}"
      loop: "{{ dns_entries }}"
      when: item.hostname not in existing_hosts
