---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  gather_facts: true
  vars:
    netbox_url: "http://192.168.253.135/api"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    pihole_api_url: "http://192.168.253.151/admin/api.php"  # no token

  tasks:

    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/dcim/devices/?tag=existing-centos"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: devices_response

    - name: Get IP addresses for each device from NetBox
      uri:
        url: "{{ netbox_url }}/dcim/interfaces/?device_id={{ item.id }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      loop: "{{ devices_response.json.results }}"
      loop_control:
        label: "{{ item.name }}"
      register: interfaces_response

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ { 'hostname': item.0.name, 'ip': item.1.json.results[0].ip | default('') | regex_replace('/\\d+$','') } ] }}"
      loop: "{{ zip(devices_response.json.results, interfaces_response.results) | list }}"
      when: item.1.json.results | length > 0

    - name: Get existing DNS entries from Pi-hole
      uri:
        url: "{{ pihole_api_url }}?list=forwarding"
        method: GET
        return_content: yes
      register: existing_pihole_dns

    - name: Normalize Pi-hole response safely
      set_fact:
        existing_hosts: "{{ existing_pihole_dns.json.data | default([]) | map(attribute='hostname') | list }}"

    - name: Add DNS entries to Pi-hole (skip existing)
      uri:
        url: "{{ pihole_api_url }}?list=forwarding&add={{ item.hostname }}&ip={{ item.ip }}"
        method: GET
      loop: "{{ dns_entries }}"
      when: item.ip != '' and item.hostname not in existing_hosts
      register: add_results

    - name: Show added results
      debug:
        var: add_results
