---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  gather_facts: yes
  become: yes

  vars:
    # === CONFIGURATION ===
    netbox_url: "http://192.168.253.135"
    netbox_token: "your_netbox_token_here"
    pihole_url: "http://192.168.253.151"   # or https://pi.hole
    pihole_password: "Root@123"
    tag_name: "existing-centos"

  tasks:

    # === Get devices tagged from NetBox ===
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        validate_certs: no
      register: netbox_devices

    # === Get IP addresses for those devices ===
    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device_id={{ item.id }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        validate_certs: no
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_ips

    # === Initialize empty dns_entries list ===
    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    # === Build dns_entries from NetBox data ===
    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ { 'hostname': item.name, 'ip': (netbox_ips.results | selectattr('item.id', 'equalto', item.id) | map(attribute='json.results') | list | flatten | map(attribute='address') | map('regex_replace', '/.*', '') | first) | default('') } ] }}"
      loop: "{{ netbox_devices.json.results }}"
      when: >
        (netbox_ips.results | selectattr('item.id', 'equalto', item.id)
        | map(attribute='json.results') | list | flatten | length) > 0

    # === Debug: Show prepared DNS entries ===
    - debug:
        var: dns_entries

    # === Authenticate with Pi-hole ===
    - name: Authenticate with Pi-hole
      uri:
        url: "{{ pihole_url }}/api/auth"
        method: POST
        body_format: json
        body:
          password: "{{ pihole_password }}"
        validate_certs: no
      register: pihole_auth

    - name: Extract session data
      set_fact:
        pihole_sid: "{{ pihole_auth.json.session.sid | default('') }}"
        pihole_csrf: "{{ pihole_auth.json.session.csrf | default('') }}"

    # === Fetch existing DNS records ===
    - name: Fetch existing Pi-hole DNS records
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts"
        method: GET
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
        validate_certs: no
      register: existing_pihole_dns

    # === Extract hostnames safely from any format ===
    - name: Extract existing DNS hostnames safely
      set_fact:
        existing_hostnames: >-
          {{
            (
              existing_pihole_dns.json.hosts.keys()
              if existing_pihole_dns.json.hosts is defined
              else (
                existing_pihole_dns.json.data | map(attribute='hostname') | list
                if existing_pihole_dns.json.data is defined
                else (
                  existing_pihole_dns.json.keys()
                  if existing_pihole_dns.json is mapping
                  else []
                )
              )
            ) | list | unique
          }}

    - debug:
        msg: "Existing hostnames found in Pi-hole: {{ existing_hostnames }}"

    # === Add new entries only if not already present ===
    - name: Add DNS entry to Pi-hole if missing
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts/{{ item.ip }}%20{{ item.hostname }}"
        method: PUT
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
        validate_certs: no
      loop: "{{ dns_entries }}"
      when: item.hostname not in existing_hostnames
      register: added_entries

    # === Debug summary ===
    - debug:
        msg: "DNS entries added: {{ added_entries.results | selectattr('status', 'defined') | list }}"
