---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: true

  vars:
    pihole_url: "https://192.168.253.151"
    pihole_password: "Root@123"
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    tag_name: "existing-centos"

  tasks:

    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_ips

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {
          'dns_hostname': item.name,
          'dns_ip': (netbox_ips.json.results
                      | selectattr('assigned_object.device.name', 'equalto', item.name)
                      | map(attribute='address')
                      | map('regex_replace', '/.*$', '')
                      | list | first | default(''))
        } ] }}"
      loop: "{{ netbox_devices.json.results }}"

    - name: Authenticate with Pi-hole
      uri:
        url: "{{ pihole_url }}/api/auth"
        method: POST
        body_format: json
        body:
          password: "{{ pihole_password }}"
        return_content: yes
        validate_certs: no
      register: pihole_auth

    - name: Extract session data
      set_fact:
        pihole_sid: "{{ pihole_auth.json.session.sid }}"
        pihole_csrf: "{{ pihole_auth.json.session.csrf }}"

    - name: Fetch existing Pi-hole DNS records
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts"
        method: GET
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
        validate_certs: no
        return_content: yes
      register: pihole_dns

    - name: Extract existing hostnames (parse clean host list)
      set_fact:
        existing_hostnames: >-
          {{
            (pihole_dns.json.config.dns.hosts | map('regex_replace', '^\\S+\\s+', '') | list)
            if (pihole_dns.json.config.dns.hosts is defined)
            else []
          }}

    - name: Debug existing hostnames
      debug:
        var: existing_hostnames

    - name: Filter DNS entries not already present
      set_fact:
        new_dns_entries: >-
          {{
            dns_entries
            | rejectattr('dns_hostname', 'in', existing_hostnames)
            | list
          }}

    - name: Debug new entries to be added
      debug:
        var: new_dns_entries

    - name: Add DNS entry using Pi-hole API
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts/{{ item.dns_ip }}%20{{ item.dns_hostname }}"
        method: PUT
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
        validate_certs: no
        status_code: [200, 201, 400]
      loop: "{{ new_dns_entries }}"
      register: result

    - name: Show result summary
      debug:
        msg: "{{ result.results | map(attribute='json') | list }}"
