---
# ============================================================
# 1. Collect Facts From All Target Hosts
# ============================================================

- name: Collect facts from all servers
  hosts: "{{ target_hosts.split(',') | map('trim') | list }}"
  gather_facts: yes
  become: yes

  vars:
    cluster_name: "centos-7"     # existing cluster
    site_name: "{{ site_name }}" # passed from Tower survey
    cluster_type: "{{ cluster_type }}"

  tasks:
    - name: Build server_info from facts
      set_fact:
        server_info:
          name: "{{ ansible_hostname }}.vgs.com"
          ip: "{{ ansible_default_ipv4.address }}/{{ (ansible_default_ipv4.address ~ '/' ~ ansible_default_ipv4.netmask) | ipaddr('prefix') }}"
          mac: "{{ ansible_default_ipv4.macaddress }}"
          interface: "{{ ansible_default_ipv4.interface }}"
          serial: "{{ ansible_product_serial | regex_replace('[^a-zA-Z0-9]', '') | truncate(50, True, '') }}"
          cluster: "{{ cluster_name }}"
          site: "{{ site_name }}"

    - name: Debug IP format
      debug:
        msg: "IP for {{ inventory_hostname }} is {{ server_info.ip }}"

# ============================================================
# 2. Push Collected Servers Into NetBox
# ============================================================

- name: Push collected servers into NetBox
  hosts: rocky-08-02
  gather_facts: no

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "668d10258cfa6ad36826afdf4c3141be6f960369"

    device_type_id: 1
    role_id: 1

  tasks:
    - name: Aggregate servers_list from hostvars
      set_fact:
        servers_list: "{{ target_hosts.split(',') | map('trim') | map('extract', hostvars, 'server_info') | list }}"

    - name: Debug servers_list
      debug:
        var: servers_list

    - name: Loop through servers and include device creation tasks
      include_tasks: modified_create_netbox_device.yml
      loop: "{{ servers_list }}"
      loop_control:
        loop_var: item
