---
- name: Collect facts from all servers
  hosts: "{{ target_hosts.split(',') | map('trim') | list }}"
  #hosts: all
  gather_facts: yes
  become: yes

  vars:
    tag: "new-build-rockyos"   # overridden by survey in Tower

  tasks:
    - name: Build server_info from facts
      set_fact:
        server_info:
          name: "{{ ansible_hostname }}.vgs.com"
          ip: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask | ipaddr('prefix') }}"
          mac: "{{ ansible_default_ipv4.macaddress }}"
          interface: "{{ ansible_default_ipv4.interface }}"
          tag: "{{ tag }}"

- name: Push collected servers into NetBox
  hosts: rocky-08-02
  gather_facts: no

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "e3ee4eda03d81a42b07de1d20064b89bba21e041"
    device_type_id: 1
    role_id: 1
    site_id: 1

  tasks:
    - name: Aggregate servers_list from hostvars
      set_fact:
        servers_list: "{{ target_hosts.split(',') | map('trim') | map('extract', hostvars, 'server_info') | list }}"

    - name: Debug servers_list
      debug:
        var: servers_list

    - name: Loop through servers and include device creation tasks
      include_tasks: modified_create_netbox_device.yml
      loop: "{{ servers_list }}"
      loop_control:
        loop_var: item
