---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: true

  vars:
    pihole_url: "http://192.168.253.151"
    pihole_password: "Root@123"
    pihole_api_script_path: /root/pihole_customdns_api/pihole-customdns.sh
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    tag_name: "existing-centos"

  tasks:

    # --- NETBOX DATA ---
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_ips

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {
          'dns_hostname': item.name,
          'dns_ip': (netbox_ips.json.results | selectattr('assigned_object.device.name', 'equalto', item.name) | map(attribute='address') | map('regex_replace', '/.*$', '') | list | first | default(''))
        } ] }}"
      loop: "{{ netbox_devices.json.results }}"

    # --- PI-HOLE AUTH ---
    - name: Authenticate with Pi-hole
      uri:
        url: "{{ pihole_url }}/api/auth"
        method: POST
        body_format: json
        body:
          password: "{{ pihole_password }}"
        validate_certs: no
        return_content: yes
      register: pihole_auth

    - name: Extract session data
      set_fact:
        sid: "{{ pihole_auth.json.session.sid }}"
        csrf: "{{ pihole_auth.json.session.csrf }}"

    # --- FETCH EXISTING DNS ---
    - name: Fetch existing Pi-hole DNS records
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts"
        method: GET
        headers:
          x-csrf-token: "{{ csrf }}"
          Cookie: "sid={{ sid }}"
        validate_certs: no
        return_content: yes
      register: existing_pihole_dns

    - name: Extract existing DNS hostnames
      set_fact:
        existing_hostnames: "{{ existing_pihole_dns.json.data | map(attribute='hostname') | list | default([]) }}"

    # --- ADD ONLY MISSING ---
    - name: Add missing DNS entries to Pi-hole
      shell: >
        {{ pihole_api_script_path }} --add {{ item.dns_hostname }} {{ item.dns_ip }}
      args:
        chdir: "{{ pihole_api_script_path | dirname }}"
      when: item.dns_hostname not in existing_hostnames
      loop: "{{ dns_entries }}"
      register: add_results

    - name: Show result
      debug:
        var: add_results.results
