---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: yes
  gather_facts: yes

  vars:
    # === NetBox configuration ===
    netbox_url: "192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"  # replace with your actual NetBox token
    netbox_tag: "existing-centos"

    # === Pi-hole configuration ===
    pihole_url: "http://192.168.253.151"
    pihole_password: "Root@123"

  tasks:
    - name: Get devices tagged from NetBox
      uri:
        url: "http://{{ netbox_url }}/api/dcim/devices/?tag={{ netbox_tag }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Get IP addresses for each device from NetBox
      uri:
        url: "http://{{ netbox_url }}/api/dcim/interfaces/?device_id={{ item.id }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_interfaces

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {'hostname': item.item.name, 'ip': (item.json.results[0].mgmt_only | ternary('', item.json.results[0].ip_address.display)) | default('', true)} ] }}"
      when: item.json.results | length > 0
      loop: "{{ netbox_interfaces.results }}"

    - name: Get existing DNS entries from Pi-hole (no token)
      shell: >
        curl -s -X GET "{{ pihole_url }}/admin/api.php?list=localdns"
      register: existing_pihole_dns

    - name: Debug Pi-hole raw response (optional)
      debug:
        var: existing_pihole_dns.stdout

    - name: Normalize Pi-hole response safely
      set_fact:
        existing_hosts: >-
          {{
            (
              existing_pihole_dns.stdout | from_json | json_query('data[].name')
            ) | default([], true)
          }}

    - name: Debug normalized host list (optional)
      debug:
        var: existing_hosts

    - name: Add DNS entries to Pi-hole (skip existing)
      shell: >
        curl -s -X POST "{{ pihole_url }}/admin/api.php" 
        --data "localdns_add={{ item.hostname }}&localdns_ip={{ item.ip }}&pw={{ pihole_password }}"
      when: item.hostname not in existing_hosts and item.ip != ''
      loop: "{{ dns_entries }}"
      register: add_results

    - name: Show added results
      debug:
        var: add_results
