---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  gather_facts: yes
  vars:
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    pihole_url: "http://192.168.253.151"
    pihole_user: "admin"
    pihole_pass: "admin"
    dns_domain: "vgs.com"
    dns_tag: "existing-centos"

  tasks:
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ dns_tag }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices
      retries: 3
      delay: 3
      until: netbox_devices.status == 200

    - name: Get IP addresses for devices
      uri:
        url: "{{ item.url }}interfaces/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_interfaces

    - name: Build list of DNS entries from NetBox
      set_fact:
        dns_entries: >-
          {{
            (dns_entries | default([]))
            + [{
                'hostname': item.json.results[0].device.display | lower,
                'ip': item.json.results[0].ip_addresses[0].address.split('/')[0]
              }]
            if item.json.results | length > 0 and item.json.results[0].ip_addresses | length > 0
            else (dns_entries | default([]))
          }}
      loop: "{{ netbox_interfaces.results }}"

    - name: Login to Pi-hole admin to get session cookies
      uri:
        url: "{{ pihole_url }}/index.php?login"
        method: POST
        body_format: form-urlencoded
        body:
          pw: "{{ pihole_pass }}"
        status_code: 302
        return_content: no
      register: pihole_login

    - name: Extract PHP session cookie
      set_fact:
        pihole_cookie: "{{ pihole_login.set_cookie | regex_search('PHPSESSID=[^;]+') }}"

    - name: Get existing DNS entries from Pi-hole
      uri:
        url: "{{ pihole_url }}/api.php?list=localdns"
        method: GET
        headers:
          Cookie: "{{ pihole_cookie }}"
        return_content: yes
      register: existing_dns

    - name: Normalize Pi-hole DNS list
      set_fact:
        existing_dns_list: "{{ existing_dns.json.data | map(attribute='name') | list if existing_dns.json.data is defined else [] }}"

    - name: Add missing DNS entries to Pi-hole
      uri:
        url: "{{ pihole_url }}/admin/scripts/pi-hole/php/add.php"
        method: POST
        headers:
          Cookie: "{{ pihole_cookie }}"
        body_format: form-urlencoded
        body:
          action: "add"
          domain: "{{ item.hostname }}"
          ip: "{{ item.ip }}"
        status_code: 200
      loop: "{{ dns_entries }}"
      when: item.hostname not in existing_dns_list
      register: add_results

    - name: Show results
      debug:
        var: add_results.results
