---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  gather_facts: yes
  vars:
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    pihole_api_token: "your_pihole_api_token_here"
    pihole_url: "http://192.168.253.151/api"

  tasks:

    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag=existing-centos"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        return_content: yes
      register: netbox_devices

    - name: Get IP addresses for each device from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device_id={{ item.id }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        return_content: yes
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_ips

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [{'hostname': item.json.results[0].assigned_object.device.name, 'ip': (item.json.results[0].address | regex_replace('/32', ''))}] }}"
      loop: "{{ netbox_ips.results }}"
      when: item.json.results | length > 0

    - name: Show prepared DNS entries
      debug:
        var: dns_entries

    - name: Get existing DNS entries from Pi-hole
      uri:
        url: "{{ pihole_url }}?list=local_dns&auth={{ pihole_api_token }}"
        method: GET
        return_content: yes
      register: existing_dns
      failed_when: existing_dns.status not in [200]

    - name: Parse existing DNS entries
      set_fact:
        existing_dns_list: "{{ existing_dns.json.data | map(attribute='name') | list | default([]) }}"

    - name: Add DNS entries to Pi-hole if not existing
      uri:
        url: "{{ pihole_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          auth: "{{ pihole_api_token }}"
          action: "add_dns_record"
          domain: "{{ item.hostname }}"
          ip: "{{ item.ip }}"
        status_code: [200]
      loop: "{{ dns_entries }}"
      when: item.hostname not in existing_dns_list
      register: add_results

    - name: Show DNS add results
      debug:
        var: add_results
