---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: true

  vars:
    tag_name: "existing-centos"
    pihole_api_script_path: /root/pihole_customdns_api/pihole-customdns.sh
    netbox_url: "http://192.168.253.135"
    netbox_token: "YOUR_VALID_NETBOX_TOKEN"

  tasks:

    # 🔹 Get devices with specific tag
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    # 🔹 Get IP address per device
    - name: Get IP addresses for each device from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device={{ item.name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_ips

    # 🔹 Initialize list
    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    # 🔹 Build DNS entries
    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {
          'hostname': item.item.name,
          'ip': (item.json.results | map(attribute='address') | map('regex_replace', '/.*$', '') | list | first)
        } ] }}"
      loop: "{{ netbox_ips.results | selectattr('json.results', 'defined') | selectattr('json.results', '!=', []) | list }}"

    - name: Show prepared DNS entries
      debug:
        var: dns_entries

    # 🔹 Get existing Pi-hole DNS entries
    - name: Get existing DNS entries from Pi-hole
      shell: >
        curl -sk -X GET "https://pi.hole/api/config/dns/hosts"
      register: existing_pihole_dns
      changed_when: false

    # 🔹 Normalize possible JSON structures
    - name: Normalize Pi-hole response
      set_fact:
        existing_hostnames: >-
          {{
            (
              (existing_pihole_dns.stdout | from_json | json_query('hosts') | default([]))
              +
              (existing_pihole_dns.stdout | from_json | json_query('data') | default([]))
              +
              (existing_pihole_dns.stdout | from_json | default([]) if (existing_pihole_dns.stdout | from_json) is iterable else [])
            )
            | map(attribute='hostname')
            | list
            | unique
          }}

    - name: Debug existing Pi-hole entries
      debug:
        msg: "{{ existing_hostnames }}"

    # 🟢 Filter only missing entries
    - name: Filter only missing DNS entries
      set_fact:
        new_dns_entries: "{{ dns_entries | rejectattr('hostname', 'in', existing_hostnames) | list }}"

    - name: Debug new DNS entries to add
      debug:
        var: new_dns_entries

    # 🔹 Add DNS entries
    - name: Add DNS entry using Pi-hole API script
      shell: >
        {{ pihole_api_script_path }} --add {{ item.hostname }} {{ item.ip }}
      args:
        chdir: "{{ pihole_api_script_path | dirname }}"
      loop: "{{ new_dns_entries }}"
      when: new_dns_entries | length > 0
      register: result

    - name: Show Pi-hole update result
      debug:
        var: result.results
