---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: true

  vars:
    pihole_url: "https://192.168.253.151"   # or use "https://192.168.253.151"
    pihole_password: "Root@123"
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    tag_name: "existing-centos"

  tasks:
    # --- 1. Get devices tagged from NetBox ---
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ tag_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    # --- 2. Get IP addresses from NetBox ---
    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_ips

    # --- 3. Initialize DNS list ---
    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    # --- 4. Build DNS entries from NetBox ---
    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {
          'dns_hostname': item.name,
          'dns_ip': (netbox_ips.json.results
                      | selectattr('assigned_object.device.name', 'equalto', item.name)
                      | map(attribute='address')
                      | map('regex_replace', '/.*$', '')
                      | list
                      | first
                      | default(''))
        } ] }}"
      loop: "{{ netbox_devices.json.results }}"

    # --- 5. Authenticate with Pi-hole ---
    - name: Authenticate with Pi-hole
      uri:
        url: "{{ pihole_url }}/api/auth"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          password: "{{ pihole_password }}"
        validate_certs: no
        return_content: yes
      register: pihole_auth

    - name: Extract session data
      set_fact:
        pihole_sid: "{{ pihole_auth.json.session.sid }}"
        pihole_csrf: "{{ pihole_auth.json.session.csrf }}"

    # --- 6. Fetch existing Pi-hole DNS records ---
    - name: Fetch existing Pi-hole DNS records
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts"
        method: GET
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
        validate_certs: no
        return_content: yes
      register: pihole_dns

    # --- (Optional) Debug the Pi-hole DNS response ---
    - name: Debug Pi-hole DNS response
      debug:
        var: pihole_dns.json

    # --- 7. Extract existing hostnames (Fixed for new Pi-hole format) ---
    - name: Extract existing hostnames (handle both old/new Pi-hole formats)
      set_fact:
        existing_hosts: >-
          {{ (pihole_dns.json.data | default(pihole_dns.json) | map(attribute='host') | list) | default([]) }}

    - name: Debug existing hostnames
      debug:
        var: existing_hosts

    # --- 8. Filter only new entries ---
    - name: Filter DNS entries not already present
      set_fact:
        new_dns_entries: "{{ dns_entries | rejectattr('dns_hostname', 'in', existing_hosts) | list }}"

    - name: Debug new entries to be added
      debug:
        var: new_dns_entries

    # --- 9. Add DNS entries to Pi-hole ---
    - name: Add DNS entry using Pi-hole API
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts/{{ item.dns_ip }}%20{{ item.dns_hostname }}"
        method: PUT
        headers:
          Cookie: "sid={{ pihole_sid }}"
          x-csrf-token: "{{ pihole_csrf }}"
          Content-Type: "application/json"
        validate_certs: no
      loop: "{{ new_dns_entries }}"
      when: item.dns_ip != ""
      register: result

    # --- 10. Show result ---
    - name: Show result summary
      debug:
        var: result.results
