---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  become: false
  gather_facts: true

  vars:
    pihole_url: "http://192.168.253.151"
    pihole_password: "Root@123"
    netbox_url: "http://192.168.253.135"
    netbox_token: "9b4a50deab2e75a51c90f2efb74d2893c9f4e8e7"  # update yours
    netbox_tag: "existing-centos"

  tasks:
    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ netbox_tag }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: true
      register: netbox_devices

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device_id={{ item.id }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: true
      loop: "{{ netbox_devices.json.results }}"
      register: netbox_ips

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [ {'hostname': item.name, 'ip': (netbox_ips.results | selectattr('item.id','equalto', item.id) | map(attribute='json.results.0.address') | map('regex_replace','/.*','') | list | first) | default('') } ] }}"
      loop: "{{ netbox_devices.json.results }}"

    - name: Show prepared DNS entries
      debug:
        var: dns_entries

    - name: Authenticate with Pi-hole
      uri:
        url: "{{ pihole_url }}/api/auth"
        method: POST
        body_format: json
        body:
          password: "{{ pihole_password }}"
        return_content: true
      register: pihole_auth

    - name: Extract session data
      set_fact:
        sid: "{{ pihole_auth.json.session.sid }}"
        csrf: "{{ pihole_auth.json.session.csrf }}"

    - name: Fetch existing Pi-hole DNS records
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts"
        method: GET
        headers:
          Cookie: "sid={{ sid }}"
        return_content: true
      register: existing_pihole_hosts

    - name: Extract existing DNS hostnames safely
      set_fact:
        existing_hostnames: "{{ existing_pihole_hosts.json | default([]) | json_query('[*].name') | default([]) }}"
      when: existing_pihole_hosts.json is defined

    - name: Show found hostnames
      debug:
        msg: "Existing hostnames found in Pi-hole: {{ existing_hostnames | default([]) }}"

    - name: Add DNS entry to Pi-hole if missing
      uri:
        url: "{{ pihole_url }}/api/config/dns/hosts/{{ item.ip }}%20{{ item.hostname }}"
        method: PUT
        headers:
          Cookie: "sid={{ sid }}"
          x-csrf-token: "{{ csrf }}"
          Content-Type: "application/json"
        status_code: [200, 201, 400]  # ✅ accept success or 'already exists'
        return_content: true
      loop: "{{ dns_entries }}"
      when: item.hostname not in existing_hostnames | default([])
      register: add_dns
      failed_when: false  # ✅ prevents failure exit on harmless errors

    - name: Show result summary
      debug:
        msg: "{{ add_dns.results | map(attribute='json') | list }}"
