---
- name: Add multiple DNS entries to Pi-hole via API (skip existing)
  hosts: dns-server-01
  gather_facts: yes
  vars:
    netbox_url: "http://192.168.253.135"
    netbox_token: "f68492e4231a818bc477b65295c660b2409cddde"
    netbox_tag: "existing-centos"

    pihole_url: "http://127.0.0.1/admin/api.php"
    pihole_token: "your_pihole_token_here"

  tasks:

    - name: Get devices tagged from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?tag={{ netbox_tag }}"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: devices

    - name: Get IP addresses for each device from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device_id={{ item.id }}"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      loop: "{{ devices.json.results }}"
      register: device_ips

    - name: Initialize dns_entries list
      set_fact:
        dns_entries: []

    - name: Build dns_entries from NetBox data
      set_fact:
        dns_entries: "{{ dns_entries + [{'hostname': item.item.name, 'ip': (item.json.results[0].address | regex_replace('/32', ''))}] }}"
      loop: "{{ device_ips.results }}"
      when: item.json.results | length > 0

    - name: Show prepared DNS entries
      debug:
        var: dns_entries

    # 🔹 Fetch current local DNS records from Pi-hole
    - name: Get existing DNS entries from Pi-hole
      uri:
        url: "{{ pihole_url }}?list=local_dns&auth={{ pihole_token }}"
        method: GET
        return_content: yes
      register: pihole_dns

    - name: Normalize Pi-hole response
      set_fact:
        existing_entries: >-
          {{
            (pihole_dns.json.local_dns
              if (pihole_dns.json is mapping and 'local_dns' in pihole_dns.json)
              else [])
          }}

    - name: Debug existing Pi-hole entries
      debug:
        var: existing_entries

    # 🟢 Filter only missing entries
    - name: Filter only missing DNS entries
      set_fact:
        missing_dns: >-
          {{
            dns_entries | rejectattr('hostname', 'in', existing_entries | map(attribute='name') | list)
                        | list
          }}

    - name: Show missing DNS entries to be added
      debug:
        var: missing_dns

    # 🟣 Add only missing entries to Pi-hole
    - name: Add missing DNS entries to Pi-hole
      uri:
        url: "{{ pihole_url }}?list=local_dns&auth={{ pihole_token }}"
        method: POST
        body_format: form-urlencoded
        body:
          action: "add"
          name: "{{ item.hostname }}"
          ip: "{{ item.ip }}"
        status_code: [200, 204]
      loop: "{{ missing_dns }}"
      when: missing_dns | length > 0

    - name: Summary
      debug:
        msg: "✅ Added {{ missing_dns | length }} new DNS entries successfully."
