---
- name: Dynamic Patching via NetBox Repo Context
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    # --- PHASE 0: LOAD DATA ---
    - name: Load NetBox Context
      set_fact:
        nb_ctx: "{{ config_context[0] }}"
      when: config_context is defined

    # --- PHASE 1: CLEAN & RE-CREATE REPOS ---
    - name: Find existing CentOS repo files
      find:
        paths: /etc/yum.repos.d/
        patterns: 'CentOS-*'
      register: old_repos

    - name: Remove existing CentOS repos
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_repos.files }}"

    - name: Generate Repos from NetBox Data
      copy:
        dest: "/etc/yum.repos.d/{{ item.id }}.repo"
        content: |
          [{{ item.id }}]
          name={{ item.name }}
          baseurl={{ nb_ctx.httpd_server_url }}{{ item.folder }}/
          enabled=1
          gpgcheck=0
          sslverify=0
      loop: "{{ nb_ctx.repositories }}"
      when: nb_ctx.repositories is defined

    # --- PHASE 2: UPDATE EXECUTION ---
    - name: Refresh Cache and Update
      block:
        - name: Clean YUM cache
          command: yum clean all

        - name: Update all packages
          yum:
            name: '*'
            state: latest
            skip_broken: yes
            update_cache: yes
          register: yum_result

        - name: Reboot if kernel/system updated
          reboot:
            reboot_timeout: 600
          when: yum_result.changed

    - name: Verification
      command: uname -r
      register: kernel_ver

    - name: Display Status
      debug:
        msg: "Update complete on {{ inventory_hostname }}. Active Kernel: {{ kernel_ver.stdout }}"
