---
# --- PHASE 0: PREPARE DATA ---
- name: Phase 0 - Map Inventory Data
  hosts: all
  gather_facts: no
  tasks:
    - name: Load and normalize NetBox config context
      set_fact:
        # We take the flat config_context and assign it to nb_ctx for your roles
        nb_ctx: "{{ config_context }}"
      when: config_context is defined

    - name: Validate merged context
      ansible.builtin.assert:
        that:
          - nb_ctx.vcenter_hostname is defined
          - nb_ctx.vm_root_password is defined
          - nb_ctx.centos_template_name is defined or nb_ctx.rockyos_template_name is defined
        fail_msg: "Variables missing! Ensure Netbox JSON is 'Flat' (no nb_ctx wrapper)."

# --- PHASE 1: DNS REGISTRATION ---
- name: Phase 1 - Register DNS entries on Pi-hole
  hosts: dns-server-01
  become: yes
  tasks:
    - name: Execute Pi-hole script
      ansible.builtin.shell: "/root/pihole-customdns.sh --add {{ item }}.{{ hostvars[item].nb_ctx.guest_domain }} {{ hostvars[item].ansible_host }}"
      loop: "{{ ansible_play_batch | reject('match', 'dns-server-01|localhost') | list }}"

# --- PHASE 2: VCENTER PROVISIONING ---
- name: Phase 2 - Create VMs
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create VM from Template
      community.vmware.vmware_guest:
        hostname: "{{ hostvars[item].nb_ctx.vcenter_hostname }}"
        username: "{{ hostvars[item].nb_ctx.vcenter_username }}"
        password: "{{ hostvars[item].nb_ctx.vcenter_password }}"
        validate_certs: false
        datacenter: "{{ hostvars[item].nb_ctx.datacenter_name }}"
        folder: "{{ hostvars[item].nb_ctx.folder }}"
        name: "{{ item }}"
        state: poweredon
        # Dynamically picks CentOS or Rocky template from the flat context
        template: "{{ hostvars[item].nb_ctx.centos_template_name | default(hostvars[item].nb_ctx.rockyos_template_name) }}"
        networks:
          - name: "{{ hostvars[item].nb_ctx.vm_network }}"
            ip: "{{ hostvars[item].ansible_host }}"
            netmask: "{{ hostvars[item].nb_ctx.netmask }}"
            gateway: "{{ hostvars[item].nb_ctx.gateway }}"
            dns_servers: "{{ hostvars[item].nb_ctx.dns_servers }}"
            start_connected: true
      loop: "{{ ansible_play_batch | reject('match', 'dns-server-01|localhost') | list }}"
      no_log: true

# --- PHASE 3: GUEST CONFIGURATION ---
- name: Phase 3 - OS Customization
  hosts: all
  serial: 1 
  gather_facts: no
  tasks:
    - name: Guest Configuration Block
      block:
        - name: Wait for SSH
          ansible.builtin.wait_for_connection:
            timeout: 600

        - name: Set Hostname and Network
          ansible.builtin.shell: |
            hostnamectl set-hostname {{ inventory_hostname }}.{{ nb_ctx.guest_domain }}
            OLD_NAME=$(nmcli -t -f NAME connection show --active | head -n 1)
            nmcli connection modify "$OLD_NAME" connection.id "ens192"
            nmcli connection modify "ens192" ipv4.dns "{{ nb_ctx.dns_servers | join(' ') }}"
            nmcli connection modify "ens192" ipv4.ignore-auto-dns yes
            nmcli connection up "ens192"
          become: yes
      when: inventory_hostname not in ['dns-server-01', 'localhost']
