---
- name: End-to-End VM Provisioning and Configuration
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    # --- PHASE 0: PREPARE DATA ---
    - name: Debug Raw Config Context (Troubleshooting)
      debug:
        var: config_context
      tags: [debug]

    - name: Load and normalize NetBox config context
      set_fact:
        # We ensure it looks for 'config_context' and handles it even if it's a list
        nb_ctx: "{{ (config_context | first) if (config_context is iterable and config_context is not mapping) else config_context }}"
      # Removed 'when' to force it to attempt or fail clearly
      
    - name: Verify nb_ctx was actually created
      fail:
        msg: "CRITICAL: nb_ctx is not defined! Check if NetBox is sending config_context."
      when: nb_ctx is not defined

    - name: Map Target IP
      set_fact:
        target_ip: "{{ ansible_host }}"

    # --- PHASE 1: DNS REGISTRATION ---
    - name: Execute Pi-hole script on DNS Server
      ansible.builtin.shell: "/root/pihole-customdns.sh --add {{ inventory_hostname }} {{ target_ip }}"
      delegate_to: 192.168.253.151 
      become: yes
      vars:
        # Use .get() to avoid fatal crashes if keys are missing
        ansible_user: "{{ nb_ctx.infra_dns_user }}"
        ansible_ssh_pass: "{{ nb_ctx.infra_dns_pass }}"
      when: inventory_hostname not in ['dns-server-01.vgs.com', 'localhost']

    # --- PHASE 2: VCENTER PROVISIONING ---
    - name: Create VM in vCenter
      community.vmware.vmware_guest:
        hostname: "{{ nb_ctx.vcenter_hostname }}"
        username: "{{ nb_ctx.vcenter_username }}"
        password: "{{ nb_ctx.vcenter_password }}"
        validate_certs: false
        datacenter: "{{ nb_ctx.datacenter_name }}"
        folder: "/{{ nb_ctx.datacenter_name }}/{{ nb_ctx.folder | default('vm') }}"
        name: "{{ inventory_hostname.split('.')[0] }}"
        state: poweredon
        template: "{{ nb_ctx.centos_template_name }}"
        networks:
          - name: "{{ nb_ctx.vm_network }}"
            ip: "{{ target_ip }}"
            netmask: "{{ nb_ctx.netmask }}"
            gateway: "{{ nb_ctx.gateway }}"
            dns_servers: "{{ nb_ctx.dns_servers }}"
            start_connected: true
        wait_for_ip_address: yes
      delegate_to: localhost
      when: inventory_hostname not in ['dns-server-01.vgs.com', 'localhost']

    # --- PHASE 3: GUEST CONFIGURATION ---
    - name: Guest Configuration Block
      block:
        - name: Wait for SSH (Timeout 10 mins)
          ansible.builtin.wait_for_connection:
            delay: 15
            timeout: 600

        - name: Set Hostname and Network inside Guest
          ansible.builtin.shell: |
            hostnamectl set-hostname {{ inventory_hostname }}
            OLD_NAME=$(nmcli -t -f NAME connection show --active | head -n 1)
            nmcli connection modify "$OLD_NAME" connection.id "ens192"
            nmcli connection modify "ens192" ipv4.dns "{{ nb_ctx.dns_servers | join(' ') }}"
            nmcli connection modify "ens192" ipv4.ignore-auto-dns yes
            nmcli connection up "ens192"
          become: yes
      vars:
        ansible_user: "{{ nb_ctx.vm_root_user }}"
        ansible_ssh_pass: "{{ nb_ctx.vm_root_password }}"
      when: inventory_hostname not in ['dns-server-01.vgs.com', 'localhost']
