---
# --- PHASE 0: PREPARE DATA ---
- name: Phase 0 - Map Inventory Data
  hosts: all
  gather_facts: no
  tasks:
    - name: Load and normalize NetBox config context
      set_fact:
        # This fix handles the 'list object' error by forcing a dictionary
        nb_ctx: "{{ (config_context | first) if (config_context is iterable and config_context is not mapping) else config_context }}"
      when: config_context is defined

    - name: Map Target IP
      set_fact:
        target_ip: "{{ ansible_host }}"

# --- CONSOLIDATED PHASES 1 & 2 ---
- name: Phases 1 & 2 - DNS and vCenter Provisioning
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute Pi-hole script on DNS Server
      ansible.builtin.shell: "/root/pihole-customdns.sh --add {{ inventory_hostname }}.{{ nb_ctx.guest_domain }} {{ target_ip }}"
      delegate_to: 192.168.253.151 
      become: yes
      when: inventory_hostname not in ['dns-server-01.vgs.com', 'localhost']

    - name: Create VM in vCenter
      community.vmware.vmware_guest:
        hostname: "{{ nb_ctx.vcenter_hostname }}"
        username: "{{ nb_ctx.vcenter_username }}"
        password: "{{ nb_ctx.vcenter_password }}"
        validate_certs: false
        datacenter: "{{ nb_ctx.datacenter_name }}"
        folder: "{{ nb_ctx.folder }}"
        name: "{{ inventory_hostname }}"
        state: poweredon
        template: "{{ nb_ctx.centos_template_name | default(nb_ctx.rockyos_template_name) }}"
        networks:
          - name: "{{ nb_ctx.vm_network }}"
            ip: "{{ target_ip }}"
            netmask: "{{ nb_ctx.netmask }}"
            gateway: "{{ nb_ctx.gateway }}"
            dns_servers: "{{ nb_ctx.dns_servers | default([nb_ctx.dns_primary]) }}"
            start_connected: true
      delegate_to: localhost
      no_log: true

# --- PHASE 3: GUEST CONFIGURATION ---
- name: Phase 3 - OS Customization
  hosts: all
  serial: 1 
  gather_facts: no
  tasks:
    - name: Guest Configuration Block
      block:
        - name: Wait for SSH (Timeout 10 mins)
          ansible.builtin.wait_for_connection:
            timeout: 600

        - name: Set Hostname and Network
          ansible.builtin.shell: |
            hostnamectl set-hostname {{ inventory_hostname }}.{{ nb_ctx.guest_domain }}
            OLD_NAME=$(nmcli -t -f NAME connection show --active | head -n 1)
            nmcli connection modify "$OLD_NAME" connection.id "ens192"
            nmcli connection modify "ens192" ipv4.dns "{{ nb_ctx.dns_servers | default([nb_ctx.dns_primary]) | join(' ') }}"
            nmcli connection modify "ens192" ipv4.ignore-auto-dns yes
            nmcli connection up "ens192"
          become: yes
      when: inventory_hostname not in ['dns-server-01.vgs.com', 'localhost']
