---
- name: Add multiple devices into NetBox
  hosts: rocky-08-02
  connection: local
  gather_facts: no

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "668d10258cfa6ad36826afdf4c3141be6f960369"

  tasks:

    # -------------------------------------------------------
    # 1. Convert devices_list (multiline string) into list
    # -------------------------------------------------------
    - name: Split devices_list into lines
      set_fact:
        device_lines: "{{ devices_list.split('\n') | reject('equalto','') | list }}"

    - name: Parse each line into structured objects
      set_fact:
#      device_list": "cent-07-15.vgs.com,Chennai,Dell,PowerEdge-R740,ens192,00:50:56:AA:BB:CC,192.168.253.150/24,centos-7,os-cluster
#      ipa-server-01.vgs.com,Chennai,Generic,Generic x86 Server,ens32,00:50:56:98:88:CC,192.168.253.192/24,centos-7,os-cluster

        devices: "{{ devices | default([]) + [ {
          'device_name': item.split(',')[0] | trim,
          'site_name': item.split(',')[1] | trim,
          'manufacturer_name': item.split(',')[2] | trim,
          'device_type_name': item.split(',')[3] | trim,
          'interface_name': item.split(',')[4] | trim,
          'mac_address': item.split(',')[5] | trim,
          'ip_address': item.split(',')[6] | trim,
          'cluster_name': item.split(',')[7] | trim,
          'cluster_type': item.split(',')[8] | trim
        } ] }}"
      loop: "{{ device_lines }}"

    - name: Debug parsed devices
      debug:
        var: devices

    # -------------------------------------------------------
    # 2. Loop through each device and create in NetBox
    # -------------------------------------------------------
    - name: Process each device
      include_tasks: create_single_device.yml
      loop: "{{ devices }}"
      loop_control:
        loop_var: item
