---
- name: Dynamic Patching Rocky Linux 8 via NetBox Context
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    # --- PHASE 0: LOAD DATA ---
    - name: Load NetBox Context
      set_fact:
        nb_ctx: "{{ config_context[0] }}"
      when: config_context is defined
      tags: always

    # --- PHASE 1: REPO MANAGEMENT ---
    - name: Find existing repo files
      find:
        paths: /etc/yum.repos.d/
        patterns: '*.repo'
      register: existing_repos

    - name: Remove old repos to ensure clean source
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ existing_repos.files }}"

    - name: Generate Rocky 8 Repos from NetBox Data
      copy:
        dest: "/etc/yum.repos.d/{{ item.id }}.repo"
        content: |
          [{{ item.id }}]
          name={{ item.name }}
          baseurl={{ nb_ctx.httpd_server_url }}{{ item.folder }}/
          enabled=1
          gpgcheck=0
          module_hotfixes=true
      loop: "{{ nb_ctx.repositories }}"
      when: nb_ctx.repositories is defined

    # --- PHASE 2: UPDATE EXECUTION ---
    - name: Patching Operations
      block:
        - name: Clean DNF cache
          command: dnf clean all

        - name: Update all packages to latest
          dnf:
            name: '*'
            state: latest
            update_cache: yes
            nobest: yes
          register: dnf_result

        - name: Check if a reboot is required
          shell: dnf needs-restarting -r
          register: reboot_required
          failed_when: false
          changed_when: false

        - name: Reboot if packages were changed or kernel update detected
          reboot:
            reboot_timeout: 600
            msg: "Rebooting after Rocky 8 patch application"
          when: dnf_result.changed or (reboot_required.rc is defined and reboot_required.rc != 0)

    # --- PHASE 3: VERIFICATION ---
    - name: Capture Final System Status
      shell: |
        echo "OS: $(cat /etc/redhat-release)"
        echo "Kernel: $(uname -r)"
        echo "Uptime: $(uptime -p)"
      register: system_info

    - name: Display Status Report
      debug:
        msg: 
          - "Patching Complete for {{ inventory_hostname }}"
          - "Details: {{ system_info.stdout_lines }}"
