---
- name: Rocky 8 Repo Server → HTTPS + HTTP to HTTPS redirect (Final Working Version)
  hosts: all
  become: yes
  vars:
    fqdn: "http-server-01.vgs.com"
    ssl_key:  "/etc/pki/tls/private/pvt.pem"
    ssl_cert: "/etc/pki/tls/certs/crt.pem"

  tasks:
    - name: Create directory and mount CIFS share
      block:
        - file:
            path: /var/www/html/repo
            state: directory
            mode: '0777'
        - mount:
            path: /var/www/html/repo
            src: //192.168.31.87/ISO
            fstype: cifs
            opts: "username=vigne,password=Vigneshv12$,rw,dir_mode=0777,file_mode=0777,vers=3.0"
            state: mounted

    - name: Install required packages
      yum:
        name:
          - httpd
          - mod_ssl
          - createrepo
          - firewalld
          - openssl
        state: present

    - name: Start firewalld and allow HTTP/HTTPS
      block:
        - service:
            name: firewalld
            state: started
            enabled: yes
        - firewalld:
            service: "{{ item }}"
            permanent: yes
            immediate: yes
            state: enabled
          loop:
            - http
            - https

    - name: Allow access to /var/www/html
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "/var/www/html">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK - /var/www/html access"

    # ——— Your exact manual certificate commands (fully automated & idempotent) ———
    - name: Generate 2048-bit private key
      command: openssl genrsa -out {{ ssl_key }} 2048
      args:
        creates: "{{ ssl_key }}"

    - name: Generate self-signed certificate (365 days) with your exact subject
      command: >
        openssl req -new -x509 -days 365 -key {{ ssl_key }} -out {{ ssl_cert }}
        -subj "/C=IN/ST=Tamil Nadu/L=Chennai/O=VGS.COM/OU=VGS.COM/CN={{ fqdn }}"
      args:
        creates: "{{ ssl_cert }}"

    - name: Secure private key permissions
      file:
        path: "{{ ssl_key }}"
        mode: '0600'

    - name: Configure SSL VirtualHost (ssl.conf)
      blockinfile:
        path: /etc/httpd/conf.d/ssl.conf
        insertafter: "^<VirtualHost.*443>"
        block: |
          ServerName {{ fqdn }}
          SSLEngine on
          SSLCertificateFile {{ ssl_cert }}
          SSLCertificateKeyFile {{ ssl_key }}
        marker: "# {mark} ANSIBLE MANAGED SSL CONFIG"
      notify: restart httpd

    - name: Force HTTP → HTTPS redirect
      copy:
        dest: /etc/httpd/conf.d/ssl-redirect.conf
        content: |
          <VirtualHost *:80>
              ServerName {{ fqdn }}
              RewriteEngine On
              RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]
          </VirtualHost>
        mode: '0644'
      notify: restart httpd

    - name: Remove any broken mod_rewrite symlink
      file:
        path: /etc/httpd/conf.modules.d/00-rewrite.conf
        state: absent

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    # ——— Final verification (will PASS because we expect 301) ———
    - name: Verify Apache config is OK
      command: apachectl configtest
      changed_when: false

    - name: Test HTTP → HTTPS redirect (must return 301)
      uri:
        url: "http://{{ fqdn }}"
        follow_redirects: none
        validate_certs: no
      register: redirect_test
      delegate_to: localhost

    - name: Confirm redirect works perfectly
      assert:
        that:
          - redirect_test.status == 301
          - redirect_test.location is defined
          - "'https://' in redirect_test.location"
        success_msg: "SUCCESS → HTTP correctly redirects to HTTPS (301 → {{ redirect_test.location }})"
        fail_msg: "FAILED → No proper redirect!"

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
