---
- name: Configure HTTP server with self-signed SSL + HTTP to HTTPS redirect + Rocky repo
  hosts: all
  become: yes
  vars:
    fqdn: "http-server-01.vgs.com"
    ssl_key:  "/etc/pki/tls/private/pvt.pem"
    ssl_cert: "/etc/pki/tls/certs/crt.pem"

  tasks:
    - name: Create repo directory and mount CIFS share
      block:
        - file:
            path: /var/www/html/repo
            state: directory
            mode: '0777'
        - mount:
            path: /var/www/html/repo
            src: //192.168.31.87/ISO
            fstype: cifs
            opts: "username=vigne,password=Vigneshv12$,rw,dir_mode=0777,file_mode=0777,vers=3.0"
            state: mounted

    - name: Install required packages
      yum:
        name:
          - httpd
          - mod_ssl
          - createrepo
          - firewalld
          - openssl
        state: present

    - name: Start and enable firewalld + open ports
      block:
        - service:
            name: firewalld
            state: started
            enabled: yes
        - firewalld:
            service: "{{ item }}"
            permanent: yes
            immediate: yes
            state: enabled
          loop:
            - http
            - https

    - name: Allow /var/www/html in httpd.conf
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          <Directory "/var/www/html">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    # Your exact working manual commands – now automated and idempotent
    - name: Generate private key (idempotent)
      command: openssl genrsa -out {{ ssl_key }} 2048
      args:
        creates: "{{ ssl_key }}"

    - name: Generate self-signed certificate (365 days)
      command: >
        openssl req -new -x509 -days 365 -key {{ ssl_key }} -out {{ ssl_cert }}
        -subj "/C=IN/ST=Tamil Nadu/L=Chennai/O=VGS.COM/OU=VGS.COM/CN={{ fqdn }}"
      args:
        creates: "{{ ssl_cert }}"

    - name: Set correct permissions on private key
      file:
        path: "{{ ssl_key }}"
        mode: '0600'

    - name: Configure SSL VirtualHost (ssl.conf)
      blockinfile:
        path: /etc/httpd/conf.d/ssl.conf
        insertafter: "^<VirtualHost.*443>"
        block: |
          ServerName {{ fqdn }}
          SSLEngine on
          SSLCertificateFile {{ ssl_cert }}
          SSLCertificateKeyFile {{ ssl_key }}
        marker: "# {mark} ANSIBLE MANAGED SSL CONFIG"
      notify: restart httpd

    - name: Create HTTP to HTTPS redirect
      copy:
        dest: /etc/httpd/conf.d/ssl-redirect.conf
        content: |
          <VirtualHost *:80>
              ServerName {{ fqdn }}
              RewriteEngine On
              RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301]
          </VirtualHost>
        mode: '0644'
      notify: restart httpd

    - name: Remove broken rewrite symlink (if exists)
      file:
        path: /etc/httpd/conf.modules.d/00-rewrite.conf
        state: absent

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Verify config + redirect
      block:
        - command: apachectl configtest
          register: configtest
          changed_when: false
        - uri:
            url: "http://{{ fqdn }}"
            follow_redirects: none
            validate_certs: no
          register: redirect
          delegate_to: localhost
        - name: Assert redirect works
          assert:
            that:
              - redirect.status == 301
              - "'https://' in redirect.location"

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
