---
- name: Patching Rocky 8 server to latest version
  hosts: "{{ target_hosts }}"
  become: true
  gather_facts: true

  tasks:

    - name: Patching task
      yum:
        name: "*"
        state: latest
        update_cache: true
      register: yum_update

    - name: Reboot the server only if it is patched
      reboot:
        reboot_timeout: 300
      when: yum_update.changed

    - name: Wait for the host to come back online
      wait_for_connection:
        timeout: 300
        delay: 10

    - name: Check kernel version
      command: uname -r
      register: kernel_version

    - name: Display kernel version
      debug:
        msg: "Kernel version on {{ inventory_hostname }} is {{ kernel_version.stdout }}"
