---
- name: Provision hosts in Foreman using NetBox + Cluster + Frontend URL
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # -----------------------------
    # Foreman Frontend URL (Nginx)
    # -----------------------------
    foreman_server_url: "https://rocky-08-01.vgs.com"
    foreman_user: "admin"
    foreman_password: "zqs977dXzqfEvTML"
    validate_certs: false

    # -----------------------------
    # NetBox API
    # -----------------------------
    netbox_url: "http://netbox.vgs.com"
    netbox_token: "668d10258cfa6ad36826afdf4c3141be6f960369"

    # -----------------------------
    # AWX Survey Inputs
    # -----------------------------
    cluster_name: "{{ survey_cluster_name }}"
    cluster_type: "{{ survey_cluster_type }}"
    site_name: "{{ survey_site_name }}"
    selected_hosts: "{{ survey_selected_hosts }}"   # comma-separated list

  tasks:

    # ---------------------------------------------------------
    # Convert selected hosts from comma-separated → list
    # ---------------------------------------------------------
    - name: Convert selected hosts to list
      set_fact:
        host_list: "{{ selected_hosts.split(',') | map('trim') | list }}"

    # ---------------------------------------------------------
    # Validate cluster exists in NetBox
    # ---------------------------------------------------------
    - name: Get cluster from NetBox
      uri:
        url: "{{ netbox_url }}/api/virtualization/clusters/?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        validate_certs: false
      register: cluster_lookup

    - name: Create cluster if missing
      uri:
        url: "{{ netbox_url }}/api/virtualization/clusters/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ cluster_name }}"
          type: "{{ cluster_type }}"
          site: "{{ site_name }}"
        validate_certs: false
      when: cluster_lookup.json.count == 0

    # ---------------------------------------------------------
    # Loop through each selected host
    # ---------------------------------------------------------
    - name: Process each selected host
      include_tasks: tasks/provision_single_host.yml
      loop: "{{ host_list }}"
      loop_control:
        loop_var: host_name
