---
- name: Create CentOS host in Foreman
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - theforeman.foreman

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "ee63f94d72c6c10a5b4e2cab4edbea9af0f18ac0"

    # ✅ Foreman frontend API
    foreman_server_url: "https://rocky-08-01.vgs.com/api"
    foreman_user: "admin"
    foreman_password: "zqs977dXzqfEvTML"

    host_root_pass: "Root@123"

    # ✅ AWX survey overrides these
    cluster_name: "vgs-centos-cluster"
    target_servers:
      - cent-07-03
      - cent-07-04

  tasks:

    # ✅ Get devices from a specific cluster
    - name: Get devices from NetBox cluster
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?cluster={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    # ✅ Filter only selected servers inside the cluster
    - name: Filter only selected servers
      set_fact:
        filtered_devices: >-
          {{ netbox_devices.json.results
             | selectattr('name', 'in', target_servers)
             | list }}

    - name: Get interfaces from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_interfaces

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_ips

    - name: Initialize foreman_hosts list
      set_fact:
        foreman_hosts: []

    # ✅ Build host list with IP + MAC from NetBox
    - name: Build foreman_hosts list from NetBox data
      set_fact:
        foreman_hosts: "{{ foreman_hosts + [ {
          'vm_name': item.name,
          'vm_ip': (
              netbox_ips.json.results
              | selectattr('assigned_object.device.name', 'equalto', item.name)
              | map(attribute='address')
              | map('regex_replace', '/.*$', '')
              | list | first | default('')
          ),
          'vm_mac': (
              netbox_interfaces.json.results
              | selectattr('device.name', 'equalto', item.name)
              | map(attribute='mac_address')
              | list | first | default('')
          )
        } ] }}"
      loop: "{{ filtered_devices }}"

    # ✅ Create host in Foreman using validated IDs
    - name: Create host in Foreman
      theforeman.foreman.host:
        server_url: "{{ foreman_server_url }}"
        username: "{{ foreman_user }}"
        password: "{{ foreman_password }}"
        validate_certs: false

        name: "{{ item.vm_name }}"
        organization_id: 1
        location_id: 2
        architecture_id: 1
        domain_id: 1
        operatingsystem_id: 2
        medium_id: 15
        ptable_id: 126
        subnet_id: 1
        hostgroup_id: 1

        ip: "{{ item.vm_ip }}"
        mac: "{{ item.vm_mac }}"
        root_pass: "{{ host_root_pass }}"
        build: true
        enabled: true
      loop: "{{ foreman_hosts }}"
