---
- name: Provision hosts in Foreman using NetBox + Cluster + Frontend URL
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Foreman Frontend URL (Nginx reverse proxy)
    foreman_server_url: "https://rocky-08-01.vgs.com"
    foreman_user: "admin"
    foreman_password: "zqs977dXzqfEvTML"
    validate_certs: false

    # NetBox API
    netbox_url: "http://netbox.vgs.com"
    netbox_token: "668d10258cfa6ad36826afdf4c3141be6f960369"

    # AWX Survey Inputs 
    cluster_name: "{{ survey_cluster_name }}"
    cluster_type: "{{ survey_cluster_type }}"
    site_name: "{{ survey_site_name }}"
    selected_hosts: "{{ survey_selected_hosts }}"

    # Foreman provisioning fields Optional
    hostgroup_name: "{{ survey_hostgroup }}"
    partition_table: "{{ survey_partition_table }}"
    installation_medium: "{{ survey_installation_medium }}"
    subnet_name: "{{ survey_subnet }}"

  tasks:

    # Convert selected hosts to list
    - name: Convert selected hosts to list
      set_fact:
        host_list: "{{ selected_hosts.split(',') | map('trim') | list }}"

    # Validate required fields when no hostgroup is selected
    - name: Validate provisioning fields
      fail:
        msg: "Partition Table, Installation Medium, and Subnet are required when no Host Group is selected."
      when:
        - hostgroup_name | length == 0
        - (partition_table | length == 0) or
          (installation_medium | length == 0) or
          (subnet_name | length == 0)

    # Get cluster from NetBox
    - name: Get cluster from NetBox
      uri:
        url: "{{ netbox_url }}/api/virtualization/clusters/?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        validate_certs: false
      register: cluster_lookup

    # Create cluster if missing
    - name: Create cluster if missing
      uri:
        url: "{{ netbox_url }}/api/virtualization/clusters/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ cluster_name }}"
          type: "{{ cluster_type }}"
          site: "{{ site_name }}"
        validate_certs: false
      when: cluster_lookup.json.count == 0

    # Process each selected host
    - name: Process each selected host
      include_tasks: tasks/provision_single_host.yml
      loop: "{{ host_list }}"
      loop_control:
        loop_var: host_name
