---
- name: Create CentOS host in Foreman
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - theforeman.foreman

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "668d10258cfa6ad36826afdf4c3141be6f960369"

    foreman_server_url: "https://rocky-08-01.vgs.com"
    foreman_user: "admin"
    foreman_password: "zqs977dXzqfEvTML"

    host_root_pass: "Root@123"

    cluster_name: "vgs-centos-cluster"
    target_servers:
      - cent-07-03
      - cent-07-04

  tasks:

    - name: Get devices from NetBox cluster
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?cluster={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no
      register: netbox_devices

    - name: Filter only selected servers
      set_fact:
        filtered_devices: >-
          {{ netbox_devices.json.results
             | selectattr('name', 'in', target_servers)
             | list }}

    - name: Get interfaces from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no
      register: netbox_interfaces

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no
      register: netbox_ips

    - name: Initialize foreman_hosts list
      set_fact:
        foreman_hosts: []

    - name: Build foreman_hosts list from NetBox data
      set_fact:
        foreman_hosts: "{{ foreman_hosts + [ {
          'vm_name': item.name,
          'vm_ip': (
              netbox_ips.json.results
              | selectattr('assigned_object.device.name', 'equalto', item.name)
              | map(attribute='address')
              | map('regex_replace', '/.*$', '')
              | list | first | default('')
          ),
          'vm_mac': (
              netbox_interfaces.json.results
              | selectattr('device.name', 'equalto', item.name)
              | map(attribute='mac_address')
              | list | first | default('')
          )
        } ] }}"
      loop: "{{ filtered_devices }}"

    # ✅ Create host in Foreman
    - name: Create host in Foreman
      theforeman.foreman.host:
        server_url: "{{ foreman_server_url }}"
        username: "{{ foreman_user }}"
        password: "{{ foreman_password }}"
        validate_certs: false

        name: "{{ item.vm_name }}"

        # ✅ Use names instead of IDs
        organization: "Default Organization"
        location: "Default Location"
        architecture: "x86_64"
        domain: "vgs.com"
        operatingsystem: "CentOS 7"
        medium: "CentOSLinux"
        ptable: "Kickstart default"
        subnet: "vgs-subnet-centos"
        # hostgroup: ""  # Optional

        ip: "{{ item.vm_ip }}"
        mac: "{{ item.vm_mac }}"
        root_pass: "{{ host_root_pass }}"
        managed: true
        build: true
        enabled: true

        interfaces_attributes:
          - type: interface
            mac: "{{ item.vm_mac }}"
            ip: "{{ item.vm_ip }}"
            primary: true
            provision: true

      loop: "{{ foreman_hosts }}"
