---
- name: Prepare host data for manual creation in Foreman UI
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    netbox_url: "https://192.168.253.134"
    netbox_token: "668d10258cfa6ad36826afdf4c3141be6f960369"

    cluster_name: "vgs-centos-cluster"
    target_servers:
      - cent-07-03
      - cent-07-04

  tasks:

    - name: Get devices from NetBox cluster
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?cluster={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no
      register: netbox_devices

    - name: Filter only selected servers
      set_fact:
        filtered_devices: >-
          {{ netbox_devices.json.results
             | selectattr('name', 'in', target_servers)
             | list }}

    - name: Get interfaces from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no
      register: netbox_interfaces

    - name: Get IP addresses from NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no
      register: netbox_ips

    - name: Build host info list
      set_fact:
        host_info: "{{ host_info | default([]) + [ {
          'name': item.name,
          'ip': (
              netbox_ips.json.results
              | selectattr('assigned_object.device.name', 'equalto', item.name)
              | map(attribute='address')
              | map('regex_replace', '/.*$', '')
              | list | first | default('')
          ),
          'mac': (
              netbox_interfaces.json.results
              | selectattr('device.name', 'equalto', item.name)
              | map(attribute='mac_address')
              | list | first | default('')
          )
        } ] }}"
      loop: "{{ filtered_devices }}"

    - name: Display host data for manual Foreman creation
      debug:
        msg: |
          Host: {{ item.name }}
          IP:   {{ item.ip }}
          MAC:  {{ item.mac }}

          Use these values in Foreman UI:
            - Organization: Default Organization
            - Location: Default Location
            - Architecture: x86_64
            - Domain: vgs.com
            - OS: CentOS 7
            - Medium: CentOSLinux
            - Partition Table: Kickstart default
            - Subnet: vgs-subnet-centos
            - Root Password: Root@123
            - Managed: Yes
            - Build: Yes
            - Primary Interface: {{ item.mac }} / {{ item.ip }}

      loop: "{{ host_info }}"
