- name: Auto-register servers in NetBox
  hosts: all
  become: yes

  tasks:
    - name: Ensure python3-pip is installed
      yum:
        name: python3-pip
        state: present

    - name: Install required Python packages
      pip:
        name:
          - pynetbox
          - netifaces
        executable: pip3

    - name: Download netbox_register.py from GitHub
      get_url:
        url: https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/netbox_register.py
        dest: /usr/local/bin/netbox_register.py
        mode: '0755'

    - name: Run NetBox registration script
      command: python3 /usr/local/bin/netbox_register.py
