---
- name: Provision RockyOS VMs with static IPs and Secure Boot disabled
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_ROCKYOS_08"
    guest_id: "rhel8_64Guest"
    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"
    dns_server: "192.168.253.151"
    vm_list:
      - name: "{{ vm_name }}"
        ip: "{{ vm_ip }}"

  tasks:

    - name: Create and power on VM with static IP and Secure Boot disabled
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        guest_id: "{{ guest_id }}"
        datastore: "{{ datastore_name }}"
        template: "{{ template_name }}"
        disk:
          - size_gb: 100
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 4
          firmware: efi
          secure_boot_enabled: false
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "{{ item.ip }}"
            gateway: "{{ gateway }}"
            netmask: "{{ netmask }}"
            device_type: vmxnet3
            connected: true
            start_connected: true
        customization:
          domain: "{{ guest_domain }}"
          dns_servers:
            - "{{ dns_server }}"
          hostname: "{{ item.name }}"
        wait_for_ip_address: true
      loop: "{{ vm_list }}"
      register: rocky_vms

    - name: Wait until VM responds to SSH
      ansible.builtin.wait_for:
        host: "{{ item.ip }}"
        port: 22
        timeout: 300
        state: started
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: Force hostname inside the VM
      ansible.builtin.shell: |
        hostnamectl set-hostname {{ item.name }}.{{ guest_domain }}
        systemctl restart systemd-hostnamed
      delegate_to: "{{ item.ip }}"
      loop: "{{ vm_list }}"

    - name: Gather VM information from vCenter
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        name: "{{ item.name }}"
        datacenter: "{{ datacenter_name }}"
      loop: "{{ vm_list }}"
      register: vm_info

    - name: Display VM Name, IP, and MAC Address
      debug:
        msg: >-
          VM: {{ item.instance.hw_name }}
          IP: {{ (item.instance.hw_eth0.ipaddresses | first) | default(item.instance.ipv4, true) | default('N/A') }}
          MAC: {{ item.instance.hw_eth0.macaddress | default('MAC not found') }}
      loop: "{{ vm_info.results }}"
