- name: Configure DNS on provisioned VMs
  hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Get connection name for ens192
      shell: "nmcli -t -f NAME,DEVICE con show | grep ':ens192' | cut -d: -f1"
      register: connection_name

    - name: Set static DNS using nmcli
      shell: |
        nmcli con mod "{{ connection_name.stdout }}" ipv4.dns "192.168.253.151"
        nmcli con mod "{{ connection_name.stdout }}" ipv4.ignore-auto-dns yes
        nmcli con up "{{ connection_name.stdout }}"
      args:
        warn: false

    - name: Restart NetworkManager to apply DNS
      service:
        name: NetworkManager
        state: restarted

    - name: Verify DNS in /etc/resolv.conf
      shell: cat /etc/resolv.conf
      register: resolv_output

    - name: Show DNS config
      debug:
        var: resolv_output.stdout_lines
