# Second Play: Configure DNS
- name: Configure DNS on provisioned VMs
  hosts: "{{ target_hosts }}
  become: true
  tasks:
    - name: Set static DNS using nmcli
      shell: |
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con mod "{}" ipv4.dns "192.168.253.151"
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con mod "{}" ipv4.ignore-auto-dns yes
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con up "{}"

    - name: Verify DNS in /etc/resolv.conf
      shell: cat /etc/resolv.conf
      register: resolv_output

    - name: Show DNS config
      debug:
        var: resolv_output.stdout_lines
