---
- name: power VM off exsi
  gather_facts: no
  hosts: localhost
  tasks:
   - name: power VM off exsi
     community.vmware.vmware_guest
	  hostname: "{{ exsihost01 }}"
	  username: "{{ root }}"
	  password: "{{ root@123 }}"
	  name: "{{ ipaserver02 }}"
	  state:  poweredoff
