---
- name: Create awx username and provide sudo access
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    password: "Welcome@123"
    users:
      - name: awx

  tasks:
    - name: User creation task
      user:
        name: "{{ item.name }}"
        home: "/home/{{ item.name }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Setting password
      command: "echo '{{ item.name }}:{{ password }}' | chpasswd"
      loop: "{{ users }}"

    - name: Providing sudo access
      command: "echo '{{ item.name }}	ALL=(ALL)	NOPASSWD: /bin/su -' | sudo tee -a /etc/sudoers.d/{{ item.name }}"
      loop: "{{ users }}"
