---
- name: Create awx username and provide sudo access
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    password: "Welcome123"
    users:
      - name: awx

  tasks:
    - name: User creation task
      user:
        name: "{{ item.name }}"
        home: "/home/{{ item.name }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Setting the Password
      user:
        name: "{{ item.name }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
        update_password: always
      loop: "{{ users }}"
      no_log: true

    - name: Providing sudo access
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item.name }}"
        content: |
          {{ item.name }} ALL=(ALL) NOPASSWD: /bin/su -
        mode: '0440'
      loop: "{{ users }}"
