- name: Validate NetBox PXE + VMware context
  hosts: ansible-server-01.vgs.com
  gather_facts: false

  tasks:
    - name: Show PXE variables
      debug:
        msg:
          http_server: "{{ config_context.http_server }}"
          kickstart_url: "{{ config_context.kickstart_url }}"
          pxe_folder: "{{ config_context.pxe_folder }}"

    - name: Show VMware variables
      debug:
        msg:
          vcenter_hostname: "{{ config_context.vcenter_hostname }}"
          vcenter_username: "{{ config_context.vcenter_username }}"
