- name: Validate NetBox PXE + VMware context
  hosts: ansible-server-01.vgs.com
  gather_facts: false

  tasks:
    - name: Show PXE variables
      debug:
        msg:
          http_server: "{{ http_server }}"
          kickstart_url: "{{ kickstart_url }}"
          pxe_folder: "{{ pxe_folder }}"

    - name: Show VMware variables
      debug:
        msg:
          vcenter_hostname: "{{ vcenter_hostname }}"
          vcenter_username: "{{ vcenter_username }}"
          vm_network: "{{ vm_network }}"
