- name: Validate NetBox PXE + VMware context
  hosts: ansible-server-01.vgs.com
  gather_facts: false

  tasks:
    - name: Show PXE variables
      debug:
        msg:
          http_server: "{{ config_context[0].http_server }}"
          kickstart_url: "{{ config_context[0].kickstart_url }}"
          pxe_folder: "{{ config_context[0].pxe_folder }}"

    - name: Show VMware variables
      debug:
        msg:
          vcenter_hostname: "{{ config_context[0].vcenter_hostname }}"
          vcenter_username: "{{ config_context[0].vcenter_username }}"
          datastore: "{{ config_context[0].datastore }}"
