---
- name: Provision RockyOS VMs with static IPs
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_ROCKYOS_08"
    guest_id: "rhelos8_64Guest"
    vm_network: "VM Network"
    dns_servers:
      - "192.168.253.155"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    domain_name: "localdomain"
    vm_list:
      - name: "rocky-08-01"
        ip: "192.168.253.133"

  tasks:
    - name: Create VM and assign static IP with customization
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        guest_id: "{{ guest_id }}"
        datastore: "{{ datastore_name }}"
        template: "{{ template_name }}"
        disk:
          - size_gb: 100
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 4
          firmware: efi
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "{{ item.ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            dns_servers: "{{ dns_servers }}"
            connected: true
            start_connected: true
        customization:
          hostname: "{{ item.name }}"
          domain: "{{ domain_name }}"
          dns_servers: "{{ dns_servers }}"
          nic_setting:
            - ip: "{{ item.ip }}"
              subnet_mask: "{{ netmask }}"
              gateway: "{{ gateway }}"
      loop: "{{ vm_list }}"

    - name: Wait for VM to respond to ping
      wait_for:
        host: "{{ item.ip }}"
        timeout: 300
        state: started
      loop: "{{ vm_list }}"
      register: ping_result

    - name: Confirm VM is reachable
      debug:
        msg: "VM {{ item.item.name }} with IP {{ item.item.ip }} is up and reachable."
      loop: "{{ ping_result.results }}"
      when: not item.failed | default(false)
