# First Play: Provision VMs
- name: Provision RockyOS VMs with static IPs and Secure Boot disabled
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_ROCKYOS_08"
    guest_id: "rhel8_64Guest"
    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"
    vm_list:
      - name: rocky-08-01
        ip: 192.168.253.101
      - name: rocky-08-02
        ip: 192.168.253.102

  tasks:
    - name: Create VM with static IP, customization, and Secure Boot disabled
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        guest_id: "{{ guest_id }}"
        datastore: "{{ datastore_name }}"
        template: "{{ template_name }}"
        disk:
          - size_gb: 100
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 4
          firmware: efi
          secure_boot_enabled: false
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "{{ item.ip }}"
            gateway: "{{ gateway }}"
            netmask: "{{ netmask }}"
            device_type: vmxnet3
            connected: true
            start_connected: true
        customization:
          domain: "{{ guest_domain }}"
          dns_servers:
            - "192.168.253.151"
          hostname: "{{ item.name }}"
        wait_for_ip_address: true
      loop: "{{ vm_list }}"

    - name: Wait until VM responds to SSH
      wait_for:
        host: "{{ item.ip }}"
        port: 22
        timeout: 120
        state: started
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: Add provisioned VMs to inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: root
        ansible_password: "Root@123"
        groups: provisioned_vms
      loop: "{{ vm_list }}"


# Second Play: Configure DNS
- name: Configure DNS on provisioned VMs
  hosts: provisioned_vms
  become: true
  tasks:
    - name: Set static DNS using nmcli
      shell: |
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con mod "{}" ipv4.dns "192.168.253.151"
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con mod "{}" ipv4.ignore-auto-dns yes
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con up "{}"

    - name: Verify DNS in /etc/resolv.conf
      shell: cat /etc/resolv.conf
      register: resolv_output

    - name: Show DNS config
      debug:
        var: resolv_output.stdout_lines
