---
- name: Provision RockyOS VMs with static IPs and Secure Boot disabled
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    datacenter_name: "Datacenter"
    folder: "vm"
    datastore_name: "datastore1"
    template_name: "GOLDENTEMPLATE_ROCKYOS_08"
    guest_id: "rhel8_64Guest"
    vm_network: "VM Network"
    netmask: "255.255.255.0"
    gateway: "192.168.253.2"
    esxi_hostname: "192.168.253.128"
    guest_domain: "vgs.com"
    vm_list:
      - name: "{{ vm_name }}"
        ip: "{{ vm_ip }}"

  tasks:
    - name: Create VM with static IP, customization, and Secure Boot disabled
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder }}"
        esxi_hostname: "{{ esxi_hostname }}"
        name: "{{ item.name }}"
        state: poweredon
        guest_id: "{{ guest_id }}"
        datastore: "{{ datastore_name }}"
        template: "{{ template_name }}"
        disk:
          - size_gb: 100
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 4
          firmware: efi
          secure_boot_enabled: false
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "{{ item.ip }}"
            gateway: "{{ gateway }}"
            netmask: "{{ netmask }}"
            device_type: vmxnet3
            connected: true
            start_connected: true
        customization:
          domain: "{{ guest_domain }}"
          dns_servers:
            - "192.168.253.151"
          hostname: "{{ item.name }}"
        wait_for_ip_address: true
      loop: "{{ vm_list }}"

    - name: Wait until VM responds to ping
      ansible.builtin.wait_for:
        host: "{{ item.ip }}"
        port: 22                # Wait for SSH port if you also want SSH readiness
        timeout: 120            # 2 minutes max
        state: started
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: Ping the VM to verify connectivity
      ansible.builtin.ping:
      vars:
        ansible_host: "{{ item.ip }}"
      loop: "{{ vm_list }}"
      delegate_to: localhost

    - name: Set static DNS using nmcli
      ansible.builtin.shell: |
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con mod "{}" ipv4.dns "192.168.253.151"
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con mod "{}" ipv4.ignore-auto-dns yes
        nmcli con show | grep -i ethernet | awk '{print $1}' | xargs -I {} nmcli con up "{}"
      become: true
      delegate_to: "{{ item.ip }}"
      loop: "{{ vm_list }}"
