- name: create a new RHEL VM and update DNS
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars:
    vcenter_name: "192.168.253.129"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Vigneshv12$"
    esxi_host: "192.168.253.130"
    vm_name: "testserveransible"
    datastore_name: "datastore1"
    template_name: "rhel7-testunix01"
    vm_ip: "192.168.253.190"
    vm_password: "admin$22"
    dns_servers:
      - "192.168.253.160"
  tasks:
    - name: create a new RHEL VM
      vmware_guest:
        hostname: "{{ vcenter_name }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "Datacenter"
        folder: "/Datacenter/vm"
        name: "{{ vm_name }}"
        state: poweredon
        datastore: "{{ datastore_name }}"
        template: "{{ template_name }}"
        networks:
          - name: "VM Network"
            type: static
            ip: "{{ vm_ip }}"
            gateway: "192.168.253.2"
            netmask: "255.255.255.0"
        wait_for_ip_address: true
        customization:
         domain: "vgs.com"
         dns_servers:
          - 192.168.253.160
    - name: wait for VM to be accessible
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        delay: 10
        timeout: 300
        state: started  

    - name: register VM with Red Hat subscription
      ansible.builtin.shell: |
        subscription-manager register --username={{ redhat_username }} --password={{ redhat_password }}
        subscription-manager attach --auto
      args:
        executable: /bin/bash
      delegate_to: "{{ vm_ip }}"
      become: yes
      become_user: root
