// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRecord'](arg1, arg2, arg3);
}

export function DeleteRecord(arg1) {
  return window['go']['main']['App']['DeleteRecord'](arg1);
}

export function GetRecords() {
  return window['go']['main']['App']['GetRecords']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
