- name: Run Foreman proxy setup script from GitHub
  hosts: all
  become: true
  gather_facts: false
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Download Foreman_Proxy_Rocky.sh from GitHub to remote host
      get_url:
        url: "https://raw.githubusercontent.com/Vignesh-8419/ANSIBLE/main/Foreman_Proxy_Rocky.sh"
        dest: "/tmp/Foreman_Proxy_Rocky.sh"
        mode: '0755'
  
    - name: Create a file in tmp
      become: true
      file:
       path: /tmp/proxy_log.txt
       state: touch
       mode: '0644'

    - name: Execute Foreman_Proxy_Rocky.sh on remote host and store output
      become: true
      shell: "/tmp/Foreman_Proxy_Rocky.sh > /tmp/proxy_log.txt 2>&1"

    - name: Show Foreman proxy setup log
      command: cat /tmp/proxy_log.txt
      register: proxy_log

    - name: Print log contents
      debug:
        var: proxy_log.stdout_lines
