---
- name: Create Shared Admin User
  hosts: "{{ target_hosts.split(',') | map('trim') | map('regex_replace', '$', '*') | join(',') }}"
  gather_facts: yes
  become: yes

  vars:
    admin_user: admin

    # Replace with the output of:
    # openssl passwd -6 'Vigneshv12$'
    admin_password: "$6$TDxrkjdWRZRu8eto$Qjtyu8XXyDsNB7jAjIiw9Yr17KT/m58VDLpi.CIXEPjKf9s8kq2oIciKUvq1dG935191IyRs5tHB9ClrnOl53/"

  tasks:

    - name: Ensure wheel group exists
      group:
        name: wheel
        state: present

    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        comment: Shared Lab Administrator
        shell: /bin/bash
        groups: wheel
        append: yes
        create_home: yes
        password: "{{ admin_password }}"
        state: present

    - name: Create .ssh directory
      file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0700'

    - name: Copy shared private key
      copy:
        src: files/id_rsa
        dest: "/home/{{ admin_user }}/.ssh/id_rsa"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0600'

    - name: Copy shared public key
      copy:
        src: files/id_rsa.pub
        dest: "/home/{{ admin_user }}/.ssh/id_rsa.pub"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0644'

    - name: Install shared authorized key
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"

    - name: Configure SSH client
      copy:
        dest: "/home/{{ admin_user }}/.ssh/config"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0600'
        content: |
          Host *
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
              LogLevel ERROR

    - name: Enable passwordless sudo
      copy:
        dest: /etc/sudoers.d/admin
        owner: root
        group: root
        mode: '0440'
        content: |
          admin ALL=(ALL) NOPASSWD: ALL
        validate: '/usr/sbin/visudo -cf %s'

    - name: Restore SELinux context
      command: restorecon -Rv /home/{{ admin_user }}/.ssh
      changed_when: false
      failed_when: false

    - name: Verify admin user
      command: id {{ admin_user }}
      register: verify_admin
      changed_when: false

    - name: Verify sudo access
      command: sudo -n whoami
      become: true
      become_user: "{{ admin_user }}"
      register: sudo_test
      changed_when: false

    - name: Display verification
      debug:
        msg:
          - "{{ verify_admin.stdout }}"
          - "Sudo User : {{ sudo_test.stdout }}"
          - "Passwordless SSH configured."
          - "Passwordless sudo configured."
