---
- name: Create Shared Admin User
  hosts: "{{ target_hosts.split(',') | map('trim') | map('regex_replace', '$', '*') | join(',') }}"
  gather_facts: yes
  become: yes

  vars:
    admin_user: admin

    # Password: Vigneshv12$
    admin_password: "$6$TDxrkjdWRZRu8eto$Qjtyu8XXyDsNB7jAjIiw9Yr17KT/m58VDLpi.CIXEPjKf9s8kq2oIciKUvq1dG935191IyRs5tHB9ClrnOl53/"

  tasks:

    - name: Ensure wheel group exists
      group:
        name: wheel
        state: present

    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        comment: Shared Lab Administrator
        shell: /bin/bash
        create_home: yes
        groups: wheel
        append: yes
        password: "{{ admin_password }}"
        state: present

    - name: Create .ssh directory
      file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: "0700"

    - name: Copy shared private key
      copy:
        src: files/id_rsa
        dest: "/home/{{ admin_user }}/.ssh/id_rsa"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: "0600"

    - name: Copy shared public key
      copy:
        src: files/id_rsa.pub
        dest: "/home/{{ admin_user }}/.ssh/id_rsa.pub"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: "0644"

    - name: Install public key
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"

    - name: Configure SSH client
      copy:
        dest: "/home/{{ admin_user }}/.ssh/config"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: "0600"
        content: |
          Host *
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
              LogLevel ERROR

    - name: Enable passwordless sudo
      copy:
        dest: /etc/sudoers.d/admin
        owner: root
        group: root
        mode: "0440"
        content: |
          admin ALL=(ALL) NOPASSWD: ALL
        validate: "/usr/sbin/visudo -cf %s"

    - name: Restore SELinux context
      command: restorecon -Rv /home/{{ admin_user }}/.ssh
      changed_when: false
      failed_when: false

    - name: Set SSH directory ownership
      file:
        path: "/home/{{ admin_user }}/.ssh"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        recurse: yes

    - name: Verify admin user
      command: id {{ admin_user }}
      register: admin_result
      changed_when: false

    - name: Verify sudo access
      become: yes
      become_user: "{{ admin_user }}"
      command: sudo -n whoami
      register: sudo_result
      changed_when: false

    - name: Display verification
      debug:
        msg:
          - "{{ admin_result.stdout }}"
          - "Sudo User : {{ sudo_result.stdout }}"
          - "Shared SSH key installed."
          - "Passwordless SSH enabled."
          - "Passwordless sudo enabled."
