// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddRecord(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRecord(arg1:number):Promise<void>;

export function GetRecords():Promise<Array<database.Record>>;

export function Greet(arg1:string):Promise<string>;
